### ISSUE TITLE
Global config fails to start if there is auto-attach assignment but the device is not plugged in

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#10080]
### Qubes OS release

Qubes OS 4.3

### Brief summary

As title says

### Steps to reproduce

1. Create auto-attach assignment based on existing device
2. Unplug the device
3. Try to start global config tool

### Expected behavior

Starts normally, possibly listing less details about the device if some are not available. But it should still be possible to:
- remove the assignment
- save without changes (should not break that assignment)

### Actual behavior

```
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/global_config.py", line 300, in do_activate
    self.perform_setup()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/global_config.py", line 422, in perform_setup
    self.handlers["attachments"] = DevAttachmentHandler(self.qapp, self.builder)
                                   ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/device_attachments.py", line 987, in __init__
    self.auto_attach_handler = AttachmentHandler(
                               ~~~~~~~~~~~~~~~~~^
        builder=gtk_builder,
        ^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        edit_dialog_class=AutoDeviceDialog,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/device_attachments.py", line 921, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        prefix=prefix,
        ^^^^^^^^^^^^^^
    ...<3 lines>...
        edit_dialog_class=edit_dialog_class,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/device_widgets.py", line 260, in __init__
    self.load_current_state()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/device_attachments.py", line 963, in load_current_state
    aw = AssignmentWrapper.new_from_existing(assignment_list)
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/device_attachments.py", line 671, in new_from_existing
    device = assignments[0].device
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/qubesadmin/device_protocol.py", line 1370, in device
    raise ProtocolError("No devices matches to assignment")
qubesadmin.device_protocol.ProtocolError: No devices matches to assignment
```

**Comment by marmarek** [comment]
@marmarta

**Comment by marmarek** [comment]
I cannot reproduce it with USB, but I can reproduce it with microphone with invalid id (which is also "device that is not connected"):
```
qvm-device mic assign testvm dom0:mic::m000000
```

I'm not sure how I got such assignment (maybe older version of global config? or some other tests), but the traceback looks quite independent of device type, so it might be happen in some cases to other devices too (?).

**Comment by Atrate** [comment]
Has this been fixed for `rc2` next week? I don't mean to be like "DEVS GO FIX", just I haven't seen any linked PRs/commits and this is kind of a deal breaker for release and will certainly prevent some people from testing the release candidates.

**Comment by marmarta** [comment]
OK, I'm trying to reproduce it with various devices, or even in tests, and I can't. I just get an unknown device row, everything functions as intended. Also can't find any core-admin/core-admin-client commits that would break this. Any more info? Anything?

**Comment by marmarta** [comment]
@Atrate , I did something that might fix this issue, but I can't reproduce it, so if you'd be willing to try it, it's at https://github.com/QubesOS/qubes-desktop-linux-manager/pull/276

**Comment by Atrate** [comment]
I don't have access to my r4.3 test machine right now, but maybe @ben-grande or @rapenne-s do and could help out with testing, as they also experienced this issue.

**Comment by ben-grande** [comment]
I didn't experienced this issue, just noted that it was a blocker.

**Comment by TheVamp** [comment]
I tried yesterday to reproduce this bug, but were half successful. I used the following commands:

- `qvm-device mic assign testvm dom0:mic::m000000`
- `qvm-device usb assign testvm dom0:mic::m000000`

I removed these entries via the Global-Config UI and applied the changes. Everything was working and I was not able to reproduce this bug. After my tries I shutdown my system.

This morning I tried to use my system again, but qubesd.service was crashing. 

The error hinted to the following [part](https://github.com/QubesOS/qubes-core-admin/blob/main/qubes/device_protocol.py#L736): 

```
    @staticmethod
    def from_str_bulk(interfaces: Optional[str]) -> List["DeviceInterface"]:
        interfaces = interfaces or ""
        if len(interfaces) % 7 != 0:
            raise QubesValueError(
                f"Invalid length of {interfaces=} "
                f"(is {len(interfaces)}, expected multiple of 7)",
            )
        return [
            DeviceInterface(interfaces[i : i + 7])
            for i in range(0, len(interfaces), 7)
        ]
```

The crash said interfaces are "None" (is 4, expected multiple of 7)

I do not know exactly how, but the state of interfaces got a None (string) value.

I repaired my system with this small patch:

```
    def from_str_bulk(interfaces: Optional[str]) -> List["DeviceInterface"]:
        interfaces = interfaces or ""
        if interfaces == "None":
            interfaces = ""
        if len(interfaces) % 7 != 0:
```
After a reboot qubesd.service was working again.

I have no idea, if this is a new bug or if this related to this bug.

**Comment by marmarta** [comment]
That's a different bug, but I thought I fixed it already... let me try to find if the fix was merged.

**Comment by marmarta** [comment]
or @marmarek will fix this, yes.

**Comment by Atrate** [comment]
`core-admin` v4.3.36 did not fix the original issue.

@marmarta your patch also doesn't seem to have done it, it changed the stack trace slightly:

```
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/device_attachments.py", line 675, in new_from_existing
    device = assignments[0].device
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/qubesadmin/device_protocol.py", line 1370, in device
    raise ProtocolError("No devices matches to assignment")
qubesadmin.device_protocol.ProtocolError: No devices matches to assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/global_config.py", line 304, in do_activate
    self.perform_setup()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/global_config.py", line 426, in perform_setup
    self.handlers["attachments"] = DevAttachmentHandler(self.qapp, self.builder)
                                   ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/device_attachments.py", line 998, in __init__
    self.auto_attach_handler = AttachmentHandler(
                               ~~~~~~~~~~~~~~~~~^
        builder=gtk_builder,
        ^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        edit_dialog_class=AutoDeviceDialog,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/device_attachments.py", line 932, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        prefix=prefix,
        ^^^^^^^^^^^^^^
    ...<3 lines>...
        edit_dialog_class=edit_dialog_class,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/device_widgets.py", line 260, in __init__
    self.load_current_state()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/device_attachments.py", line 974, in load_current_state
    aw = AssignmentWrapper.new_from_existing(assignment_list)
  File "/usr/lib/python3.13/site-packages/qubes_config/global_config/device_attachments.py", line 677, in new_from_existing
    except ProtocolError:
           ^^^^^^^^^^^^^
NameError: name 'ProtocolError' is not defined
```

Seems `ProtocolError` is not defined here. Changing this (dirtily) to a catch-all `except` makes qubes-global-config launch. Unknown devices are presented like this now:

<img width="1319" height="70" alt="Image" src="https://github.com/user-attachments/assets/5079d9ab-2c35-43aa-819f-036204fbef18" />

So if that's the intended way to display unknown devices (I did not redact anything in the screenshot), then it seems that importing ProtocolError (wherever it's declared) should fix this.

**Comment by Atrate** [comment]
Actually, the patch from @marmarta works fully, disregard my previous comment, it was just me who applied it incorrectly. I think applying it should fix the issues people are having.
