### ISSUE TITLE
debian 8 troubles after 'apt-get upgrade' (R3 rc1)

### ISSUE THREAD

**Issue by dncohen** [QubesOS/qubes-issues#1033]
Noticed this and I believe it is reproducible every time.

Start with R3 rc1.  I've run `sudo qubes-dom0-update` but not sure it that matters.  Install the debian-8 template.

Clone the debian-8 template to, say, d8-test.

Start a d8-test terminal.  Should work as expected.

In d8-test terminal, run `sudo apt-get update` and `sudo apt-get upgrade`.  Then `sudo shutdown -h now`.

Start a d8-test terminal.  This will fail to bring anything up.  Although the d8-test VM will be running, no application will show up on the GUI.

**Comment by marmarek** [comment]
It looks to be this bug:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=746415

Apparently GNOME folks are not supporting non-UTF-8 environments
anymore. Debian template on Qubes have a code to set UTF-8 as default,
but it is currently broken...

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by nrgaway** [comment]
There seems to have been an update (in my case anyway) that updated locales
which seems to have broken some apps like gnome-terminal.  gnome-terminal
requires a proper locale to be set or it will not start.

use xterm to gain access to a terminal.  You may attempt to run
gnome-terminal from xterm and if you receive some locale type message, then
try to update locale to see if this solves your issue.  Note that after
locale is updated you will need to shutdown the AppVM and restart it for
changes to take effect.

Here is one way to change locale:
localedef -f UTF-8 -i en_US -c en_US.UTF-8
update-locale LC_ALL=en_US.UTF-8

And here is another (note the lowercase use of utf8)
localedef -f UTF-8 -i en_US -c en_US.UTF-8
localectl set-locale LANG=en_US.utf8

Please report back if this helps solve your issue.

https://groups.google.com/forum/#!searchin/qubes-users/localectl|sort:relevance/qubes-users/CuC-El1qoss/dQZ7FI7UIuoJ

**Comment by marmarek** [comment]
According to https://wiki.debian.org/Locale, the preferred way to
generate locales is to use `dpkg-reconfigure locales`, not localedef
directly.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by nrgaway** [comment]
On 22 June 2015 at 16:43, Marek Marczykowski-Górecki <
notifications@github.com> wrote:

> According to https://wiki.debian.org/Locale, the preferred way to
> generate locales is to use `dpkg-reconfigure locales`, not localedef
> directly.
>

One would think that would work. It had not worked for me in the past and
recently another user stated he tried that without success.  'localctl'
seems to be part of the 'systemd' suite of packages and looks like the
preferred way of setting locale especially in relation to the newer gnome
code base?

'localectl' can not be used to set locale though when initially building
the template since it will not run in a standard 'chroot' environment.


https://groups.google.com/forum/#!searchin/qubes-users/localectl|sort:relevance/qubes-users/R5J0RddvuYU/rKMeoaGSBvYJ
> Hello,
>
> I am using debian-8 templates for my (non-net-)VMs. I noticed that locale
> is set to en_US, so I tried dpkg-reconfigure locales and built de_DE and
> set it as default in the template.
>
> However this does not fix this issue. How can I properly change the
> template to German (or autodetect from dom0) so I have everything localized?
>
> Thanks in advance
>
> Christian
>

**Comment by marmarek** [comment]
On Sun, Jun 21, 2015 at 06:58:11PM -0700, dncohen wrote:
> Noticed this and I believe it is reproducible every time.
> 
> Start with R3 rc1.  I've run `sudo qubes-dom0-update` but not sure it that matters.  Install the debian-8 template.
> 
> Clone the debian-8 template to, say, d8-test.
> 
> Start a d8-test terminal.  Should work as expected.
> 
> In d8-test terminal, run `sudo apt-get update` and `sudo apt-get upgrade`.  Then `sudo shutdown -h now`.
> 
> Start a d8-test terminal.  This will fail to bring anything up.  Although the d8-test VM will be running, no application will show up on the GUI.

I hope it is fixed in qubes-core-agent-3.0.12 - it should regenerate
UTF-8 locale.

Updated package qubes-core-agent-3.0.12 is uploaded to testing
repository. If you want to install it, you need to edit
/etc/apt/sources.list.d/qubes-r3.list and uncomment jessie-testing
repository definition.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
This is in essence how grml-debootstrap handles locales at Debian base image creation:
* installs the `locales` package
* copies [/etc/debootstrap/locale.gen](https://github.com/grml/grml-debootstrap/blob/master/locale.gen) into chroot as /etc/debootstrap/locale.gen
* run `update-locale LANGUAGE=en_US:en LANG=en_US.UTF-8`
* hopefully, I have forgotten nothing, but I will argue we should leave such tasks to tools that are dedicated to this anyhow in #1055

This is a non-issue for [non-Qubes] Whonix 11, which is based on Debian 8 (jessie). Setting to UTF by default works fine. Regeneration of locales by any system triggers is also a non-issue. Using the most canonical way to be as close to Debian as possible for best stability.

> One would think that would work. It had not worked for me in the past and recently another user stated he tried that without success.

So we have an issue here, that we don't really understand, haven't reported upstream, and try solving somehow out-own-way(tm). Not good.

**Comment by yawnbox** [comment]
This thread helped me resolve this issue.

1. select "debian-8: Add more shotcuts..."
2. select "Xtem" application and add to the menu list
3. open "Xtem"
4. enter "sudo dpkg-reconfigure locales"
5. select "en_US.UTF-8 UTF-8" and hit <Ok>
6. select "en_US.UTF-8" as the Default locale for the system environment" and hit <Ok>
6. Restart "debian-8" VM

Thank you all.

**Comment by marmarek** [comment]
Fixed here: qubesos/qubes-core-agent-linux@b368ffe5c690feea416274ddffcca272bcb71892

**Comment by iuriguilherme** [comment]
`sudo dpkg-reconfigure locales` on the debian-8 template haven't helped, when trying to launch terminal from menu in an AppVM with debian-8 template, it still doesn't show up. Also, once it crashed the Qubes VM Manager.

I'm still right-clicking on the AppVM and running `x-terminal-emulator`.

PS: I used "pt_BR.UTF-8" as locale.
