### ISSUE TITLE
Remove ads from dev.qubes-os.org

### ISSUE THREAD

**Issue by parulin** [QubesOS/qubes-issues#10469]
### The problem you're addressing (if any)

As mentioned by @RandyTheOtter [on the forum](https://forum.qubes-os.org/t/why-do-we-have-ads-in-qubes-dev-documentation/37698), there are some ads on https://dev.qubes-os.org

For example, at the bottom of the [index of core-admin](https://dev.qubes-os.org/projects/core-admin/en/latest/), there is one line containing some ads about Amazon, MongoDB or else.

### The solution you'd like

No ads.

### The value to a user and who that user might be

The user can focus on the content of the docs without being distracted.

### Completion criteria checklist

(This section is for developer use only. Please do not modify it.)

**Comment by marmarek** [comment]
Hm, now that main documentation is on RTD, maybe we don't need separate dev.qubes-os.org anymore and can simply merge them?

**Comment by parulin** [comment]
That's a good idea, it would also fix:

- #10220

**Comment by ben-grande** [comment]
Would also fix:

- https://github.com/qubesos/qubes-issues/issues/6080

**Comment by marmarek** [comment]
> Hm, now that main documentation is on RTD, maybe we don't need separate dev.qubes-os.org anymore and can simply merge them?

Done. I moved subprojects to doc.qubes-os.org, and set redirect dev.qubes-os.org  -> doc.qubes-os.org.

**Comment by ben-grande** [comment]
This issue is about ads on the docs. I still see this banner at the bottom of [doc.qubes-os.org/projects/core-admin](https://doc.qubes-os.org/projects/core-admin/en/latest/) the page:

```
[EthicalAds is a GDPR-compliant ad network for devs No cookie banners, and only dev-focused ads.](https://server.ethicalads.io/proxy/click/8173/019f9285-20d0-7281-9e30-240025d263c0/)
[Ads by EthicalAds](https://www.ethicalads.io/advertisers/topics/backend-web/?ref=ea-text)
```

Also, this might redirect might have broken something (I am not sure if it was broken before):

- https://doc.qubes-os.org/projects/core-admin/en/latest/qubes-api.html#qubes.api.admin

```
qubes.api.admin

    alias of <module ‘qubes.api.admin’ from ‘/home/docs/checkouts/readthedocs.org/user_builds/qubes-core-admin/checkouts/latest/qubes/api/admin.py’>
```

**Comment by parulin** [comment]
http://dev.qubes-os.org/projects/qubes-core-qrexec is now named `core-qrexec`, which is good but the redirection fails and so do intersphinx when building the docs.

**Comment by andrewdavidwong** [comment]
> This issue is about ads on the docs. I still see this banner at the bottom of [doc.qubes-os.org/projects/core-admin](https://doc.qubes-os.org/projects/core-admin/en/latest/) the page:
> 
> ```
> [EthicalAds is a GDPR-compliant ad network for devs No cookie banners, and only dev-focused ads.](https://server.ethicalads.io/proxy/click/8173/019f9285-20d0-7281-9e30-240025d263c0/)
> [Ads by EthicalAds](https://www.ethicalads.io/advertisers/topics/backend-web/?ref=ea-text)
> ```
> 

Reopening and updating title.

> Also, this might redirect might have broken something (I am not sure if it was broken before):
> 
> * https://doc.qubes-os.org/projects/core-admin/en/latest/qubes-api.html#qubes.api.admin
> 
> ```
> qubes.api.admin
> 
>     alias of <module ‘qubes.api.admin’ from ‘/home/docs/checkouts/readthedocs.org/user_builds/qubes-core-admin/checkouts/latest/qubes/api/admin.py’>
> ```

> http://dev.qubes-os.org/projects/qubes-core-qrexec is now named `core-qrexec`, which is good but the redirection fails and so do intersphinx when building the docs.

IMO, these should be separate bug report issues, since they're not about removing ads from the docs.

**Comment by parulin** [comment]
@marmarek from your comment here: https://github.com/QubesOS/qubes-issues/issues/5246#issuecomment-5069056987 ... does it mean that the main project is a paid plan while the subprojects are free plans, so that's why we have ads with them?

On [my fork of qubes-doc](https://github.com/parulin/qubes-doc/tree/add-subprojects), I tried to see if it is possible to build all Qubes documentation in one project only using the suggested git submodules. It was intended for #11009 but could it resolve this issue?
