### ISSUE TITLE
Create New VM dialog inconsistent handling of Standalone + HVM

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#1251]
In Qubes Manager 'Create New VM' dialog window, selecting first Standalone then HVM will give you the option of choosing a template (and this appears to work). However, first selecting HVM will auto-check the Standalone option, then ghost out the template dropdown box; There is no reason given why the template option should differ from selecting dialog options in a different order.

As it is, having Standalone checked /sometimes/ results in the creation of a standalone HVM having a clone of an HVM template, and /sometimes/ creates an HVM with a blank root.

Expected behavior: The status of the template dropdown box should not depend on the order in which Standalone or HVM options were selected. The dialog should be normalized so that each combination of VM type + Standalone produces a unique and discernible state. An additional radio button, checkbox or dropdown box item may be what's needed to clarify the operation of this UI function.

**Comment by marmarek** [comment]
Original intention was to provide only two options:
1. New, blank standalone HVM (so no template option allowed)
2. Template-based HVM

But you're right, this approach is wrong.

**Comment by ttasket** [comment]
It seems that a third option is manifesting: A new Standalone HVM that gets a cloned root from a template. Is this useful?

**Comment by marmarek** [comment]
I don't know, do you see any use case for it? I need to be consistent,
but I have no opinion whether "standalone HVM created from template"
should be supported or not.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by 3n7r0p1** [comment]
> I have no opinion whether "standalone HVM created from template"
should be supported or not.

I may be missing something obvious but why would need for this case (template-based standalone HVM) differ any from need for its PVM counterpart?

> do you see any use case for it?

Windows, specifically, has a torturous update and config process. If I need a persistent file system, it would be beneficial to be able to fork a standaloneVM from a Windows template, instead of having to start from blank. The other option would be to clone and use the templateVM but that would obviously not be canonical use of a templateVM.

**Comment by unman** [comment]
@andrewdavidwong I believe this issue is resolved in 3.2, and can be closed. The same options appear regardless of order of selection.

**Comment by tasket** [comment]
@unman If one or more HVM templates exist in the system, the inconsistency still occurs as described.

**Comment by tasket** [comment]
I'll try to fix this and submit a PR.

**Comment by unman** [comment]
@tasket  You are, of course, quite right. I reverted my QubesManager, removed internal mark on template and indeed the problem remains.
I would favour an additional checkbox as you suggested earlier, if that doesnt make the UI too cumbersome

**Comment by tasket** [comment]
So far I'm trying it with same checkboxes, but user can choose 'none' (default) in the template list when both HVM and Standalone are selected.
