### ISSUE TITLE
Network problems from inaccurate time after wake from sleep - R3.1rc3

### ISSUE THREAD

**Issue by ttasket** [QubesOS/qubes-issues#1795]
User space programs like openvpn and some web sites are experiencing problems because VM date/time is not updated for a very long period after wake from sleep. In the case of openvpn, downstream VMs must wait the entire time (60-120 sec) until a timeout occurs before communication can resume. Normally, a timeout would occur instantly after wake and communication would resume a few seconds later.

This started happening right after I updated to rc3.

I ran some tests and found out that domUs will not get time sync'd for 10 minutes or more after waking from sleep!

**Comment by marmarek** [comment]
I think this is already fixed here: https://github.com/QubesOS/qubes-core-admin-linux/commit/ee3950a3aa47f4697b2a790d71e7468f329c921b
The update just went into stable repository, so you can simply run `qubes-dom0-update`.

**Comment by ttasket** [comment]
VMs are still not getting timely time syncs after updating and rebooting. This time it took 6 min. after waking from sleep. The VMs are all using a debian 8 template.

**Comment by marmarek** [comment]
Do you have proper time in dom0 after resume? Check logs on qubes-suspend service in dom0: `sudo journalctl -u qubes-suspend.service`, you should see `01qubes-sync-vms-clock` script running and listing your VMs - check if and when the affected VMs were listed.

**Comment by ttasket** [comment]
The dom0 time is correct right after waking. When I grep the journalctl output, the last time 01qubes-sync-vms-clock appears is around 13:00 today (several suspend cycles since then). I think this was right around the time I updated dom0.

Here are the log lines from the last time I woke the system:

Feb 28 21:09:25 dom0 systemd[1]: Unit qubes-suspend.service is not needed anymore. Stopping.
Feb 28 21:09:25 dom0 systemd[1]: Stopping Qubes suspend hooks...
Feb 28 21:09:25 dom0 51qubes-suspend-netvm[4062]: method return sender=:1.5 -> dest=:1.104 reply_serial=2
Feb 28 21:09:26 dom0 systemd[1]: Stopped Qubes suspend hooks.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.9-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/01833c698c9228892eb36b71e945f17ecb3e2666...c87d6c5cb732d80bc44fa9af6fb5459a77be0e1a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.1.9-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/01833c698c9228892eb36b71e945f17ecb3e2666...c87d6c5cb732d80bc44fa9af6fb5459a77be0e1a

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-linux-3.0.20-1.fc20` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin-linux/compare/af1a352343b1028cac7d649cb9e4f2bd731a68b3...0ac1b2cbe65bd27ad11a899bd9e692c69d887bb1
