### ISSUE TITLE
typo on backside of t-shirt

### ISSUE THREAD

**Issue by ThomasWaldmann** [QubesOS/qubes-issues#2628]
slightly unusual bug, but i thought i make an issue, so it won't be forgotten:

there is a typo on your (xxl) project t-shirt, "reasonably" is spelled like this, compare to what you see on the pic.

![qubes_os_tshirt_typo](https://cloud.githubusercontent.com/assets/356103/22865393/9f4dd4d8-f163-11e6-9545-039938b0fe60.jpg)

**Comment by andrewdavidwong** [comment]
No problem. Just put your T-shirt in the nearest 3-D printer, and we'll patch the bug remotely.

(@marmarek, I infer from your assigning @woju to this issue that it is actually somehow actionable. Assigning appropriate labels.)

**Comment by ThomasWaldmann** [comment]
2 parts:
- decide what to do with existing t-shirts (could be: "nothing", "exchange at own costs")
- avoid printing more t-shirts with the typo (update some design file somewhere?)

**Comment by marmarek** [comment]
You know, this is exclusive, limited edition ;)

**Comment by ThomasWaldmann** [comment]
"These early days, I had one of these first qubes OS t-shirts, these rare ones with the typo." :-)

**Comment by woju** [comment]
The bug was already fixed in the source during 33c3. However, like @andrewdavidwong, I'm not sure about deployment strategy. I'd close this bug if there is nothing more to do.

**Comment by canihavesomecoffee** [comment]
Just FYI, this typo was still present on the t-shirts at FOSDEM this year... Was that still the old stock perhaps?

**Comment by woju** [comment]
Yes it was.
