### ISSUE TITLE
R4.0-rc1 fails to shutdown

### ISSUE THREAD

**Issue by JPL1** [QubesOS/qubes-issues#2957]
#### Qubes OS version R4.0-rc1

Gets stuck on 'device-mapper failing to remove...' - I can check next time I shut down if you need more info

**Comment by JoeThielen** [comment]
Qubes OS version R4.0-rc1

Did this for me too.  Rebooted twice, shutdown once.  All failed with the same thing.

I had already updated Qubes via dom0, if that matters (installed & updated today).

**Comment by JoeThielen** [comment]
Screenshot attached.  There were many more instances of "Command failed" that scrolled by before this.

![errors](https://user-images.githubusercontent.com/14891634/30219658-c108bcb2-948a-11e7-90f6-0be4e0331ec9.png)

**Comment by holiman** [comment]
Having the exact same issue (and an almost identical photo). 
Running on a Librem13v2, with two ssd-disks, automatically paritioned. Always fail to shutdown, sometimes with the messages above, sometimes with just a black screen.

**Comment by holiman** [comment]
Anything I can do to help debug this? It's very annoying.

**Comment by holiman** [comment]
Anything I can do to help debug this? It's very annoying.

**Comment by marmarek** [comment]
Stopping `qubes-core.service` should shutdown all the VMs, but for some reason it doesn't work. This is why all those "Device or resource busy" errors are there.
Maybe something is wrong with ordering? Try adding `After=qubesd.service` to `/usr/lib/systemd/system/qubes-core.service`, then execute `systemctl daemon-reload` and see how it works then.

**Comment by holiman** [comment]
I was about to try this, but since I just previously did a dom0-upgrade with current-testing enabled, I thought I'd see if it had already been resolved. 

Turned out it had, seems not to be an issue any longer. LMK if you want any additional info anyway.

**Comment by holiman** [comment]
Hm, interestingly, it seems the problem was _not_ fixed by my upgrade. I used xfce for a couple of logins, instead of i3wm, and had no problems. Now, I went back to i3, and the problem was there again. 

When I exit i3, I first logout, then do a shutdown. Whereas exiting from xfce, it's a one-step process. Maybe that has something to do with it ? 

I'll retry with your suggestion later.

**Comment by SejmL** [comment]
I have a shutdown bug in qubes 4.0rc2 but my screen is totally black

**Comment by mickewen** [comment]
I see this too but shutdown always ends with a black screen but still powered up.  I've tried logging out before shutting down as well as while still logged in.  I have also done a dom0 upgrade and tried the After=qubesd.service suggestion as mentioned above although I'm not sure where to add it in the qubes-core.service file.  Any help appreciated.
Motherboard is a Gigabyte B150M-HD3, BIOS ver. F20d. 8G DDR3.
Qubes is installed on a 960 EVO NVMe, 250G.  I used the Auto option in the installer to a blank drive.
I tried doing sudo halt from dom0 as well and it seemed to do more but still ended with a black screen.

I'm happy to try things out if anyone has more suggestions.

**Comment by OldPeasant** [comment]
On my System76 Galago Pro running R4.0-rc2, shutdown always fails (black screen, but keyboard still lit) if sys-net is still running when I try to shutdown Qubes.
When I first shutdown all VMs (looks like sys-net is the bad guy) so only dom0 remains running and then shutdown, it works fine.

(I'm new to Qubes, so I don't know which additional infos might be important. Will be happy to provide additional info, just tell me what you need)

**Comment by andrewdavidwong** [comment]
> On my System76 Galago Pro running R4.0-rc2, shutdown always fails (black screen, but keyboard still lit) if sys-net is still running when I try to shutdown Qubes.
When I first shutdown all VMs (looks like sys-net is the bad guy) so only dom0 remains running and then shutdown, it works fine.

This reminds me of #1581 (see the comments for some handy scripts to automate shutting down all domUs before dom0).

**Comment by OldPeasant** [comment]
> This reminds me of #1581 (see the comments for some handy scripts to automate shutting down all domUs before dom0).
Thanks! I now use one of those scripts and shutdown is smooth!

**Comment by mickewen** [comment]
Manually shutting down sys-net works for me too.  Thanks.

**Comment by blacklight447** [comment]
I talked to a user in the unoffical telegram group which goes by the name jackpot, he's on 3.2 and seems to have the same issue. He also sended me the picture below.

![issue](https://user-images.githubusercontent.com/19261543/33981912-eef6de18-e0ae-11e7-8a9a-34cdea0f72ba.jpeg)

So  it doesn't seem to be a 4.0 specfic issue.

**Comment by JPL1** [comment]
This is fixed for me with rc3

**Comment by OldPeasant** [comment]
Same for me: Problem is resolved with 4.0-rc3. As well as starting VMs: Every now and then failed in 4.0-rc2, works just fine in 4.0-rc3. The Qubes team did a great job with rc3!

**Comment by blacklight447** [comment]
Does anyone here know then what solved the issue, and if the solution can be backported to 3.2

**Comment by tasket** [comment]
It still hangs for me sometimes when I go back to the normal shutdown procedure. For now I use a script that does `qvm-shutdown --all --wait --timeout=20; sudo shutdown -P now` and this is reliable.

I may create a service that has `conflicts=shutdown.target` and assign those commands to the service stop directive to make it all automatic.

**Comment by constantoverride** [comment]
@tasket if you feel like testing, this issue should be fixed by [this PR](https://github.com/QubesOS/qubes-gui-daemon/pull/24) which is present in `qubes-gui-dom0-4.0.8-1.29.fc25` on `qubes-dom0-unstable` repository.
