### ISSUE TITLE
VM list is too small and randomly changes in size

### ISSUE THREAD

**Issue by Zrubi** [QubesOS/qubes-issues#2970]
#### Qubes OS version (e.g., `R3.2`):
4.0-rc1
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
dom0

---

### Expected behavior:
All VMs should be visible.

### Actual behavior:
Random "tool-tip" size.
See the attached screenshots
![qubes-tray-bad](https://user-images.githubusercontent.com/7664714/28965740-e3a19d18-7912-11e7-83aa-8a8ce93c0c16.jpg)
![qubes-tray-ok](https://user-images.githubusercontent.com/7664714/28965739-e3a15dbc-7912-11e7-82c0-b8a732dbaa5d.jpg)
![qubes-tray-scroll](https://user-images.githubusercontent.com/7664714/28965741-e3a1accc-7912-11e7-825a-468343ea3876.jpg)

### Steps to reproduce the behavior:
The size of this thing is randomly changing

### General notes:
The separate Qubes Manager was much more usable, than this thing.

---

**Comment by marmarek** [comment]
Hmm, I can't reproduce. @kalkin any idea?

**Comment by SimonSelg** [comment]
I experienced this bug as well a few times, login/logout "fixed" it sometimes. Notably the size of the other widget was correct the whole time.

**Comment by kalkin** [comment]
Hmm haven't seen this yet, but I notice you have the panel at the bottom, right? I will setup my test machine accordingly and see if I get it reproduced.

**Comment by SimonSelg** [comment]
It happend on my machine with the panel on top too.

**Comment by na--** [comment]
Still present on RC2 and super annoying. Sometimes the widget is so small that only the up and down arrows are visible with VM entries totally inaccessible... 
In my case the xfce panel is on the bottom of the screen and I use a mirrored external display

**Comment by grote** [comment]
I can confirm this to be still present in RC3. Seems to be fine with two running VMs. As soon as a third is started it looks like in the op's screenshot. Seems like the height of the widget is somehow restrained (maybe depending on screen resolution?).

**Comment by andrewdavidwong** [comment]
(Updated title to be more descriptive.)

**Comment by marmarek** [comment]
The same applies to devices widget

**Comment by Zrubi** [comment]
This issue is still present in the just released 4.0

**Comment by marmarek** [comment]
Fixed version is available in testing repository - see comment above.

**Comment by Zrubi** [comment]
The issue is still there - even after I updated from the current-testing repository.

**Comment by marmarek** [comment]
Sorry for stupid question, but have you restarted the widget (logout/login for example).

**Comment by Zrubi** [comment]
:) sure.
Rebooted the whole machine, just to make sure  ;)

And the issue is the same as before.
Always reproducible, and always work as soon as I move my panel to top.
And breaks again in the bottom - as you start more VMs.

And the "spinner" is broken, in both places...

**Comment by andrewdavidwong** [comment]
Apologies to all for not reopening this sooner.

**Comment by esote** [comment]
After a recent update in dom0, I do not experience this issue any more (`qubes-desktop-linux-manager` 4.0.7-1 to 4.0.9-1). Thanks!

**Comment by keepiru** [comment]
I am still experiencing this after upgrading to qubes-desktop-linux-manager-4.0.10-1.fc25 and rebooting.  Rapid-clicking it tens of times sometimes makes it resize.  Once resized it tends to work until I start another VM.  Then it's back to scrolling.  Once interesting behavior is it often resizes 1 second after displaying the list, but keeps the scrolling buttons.

**Comment by Geblaat** [comment]
I just from to Qubes 4.0.1-rc2 from 3.2 and noticed that the device list is still to small. If there are more than 4 devices you have to scroll to see all of them. The VM list seems to be working fine(currently 10 running VM's and no need to scroll.)
My panel is on the bottom.

**Comment by andrewdavidwong** [comment]
@Geblaat, could you check to see whether you're using `qubes-desktop-linux-manager-4.0.11-1.fc25`?

**Comment by Geblaat** [comment]
> @Geblaat, could you check to see whether you're using `qubes-desktop-linux-manager-4.0.11-1.fc25`?

I'm on 4.0.13.1.fc25 already, probably because the current-testing updates are included in the 4.0.1 iso.

**Comment by Geblaat** [comment]
A reliable way to trigger the bug seems to be: 1. Click the devices gadget to show the list. 2. After that, doesn't matter if it is seconds or hours after, attach a new device. 3. Click the devices gadget again and you must scroll.
It seems the size is 'fixed' after it is opened the first time. For example if you boot, don't add any devices, click the devices gadget first(when only the internal microphone is listed), and then attach a device, the list will be unusably short. If you first attach a device, then click the gadget, attach another device, the list will be a little larger and while still very annoying, it will at least show a few items at a time, so it is kind of usable. If you first attach all your devices at once, and only then open the list, it will show everything without scrolling.

**Comment by andrewdavidwong** [comment]
I've experienced a similar problem (with probably the same underlying cause) with the Qubes Devices widget list. In my case, the list is normal in width but extremely short (see #4738 for further details).

**Comment by Geblaat** [comment]
After updating to qubes-desktop-linux-manager-4.0.15-1.fc25 there is no more scrolling in the devices list, but the size is still fixed after opening it once. So if I open it, then add a device, open it again doesn't become unusable short because the small sized is not filled with scrolling indicators, but it is still unusable because it does not become larger, so the newly added devices are not visible at all.

**Comment by Geblaat** [comment]
I just updated to qubes-desktop-linux-manager-4.0.15-1.fc25, and it fixes all my issues with the Devices widget, thanks!
However, it looks like the VM widget is constantly crashing. After booting, the icons all move a place to the left, as if the VM widget is appearing, however it doesn't appear and the icons move back to the right. This keeps happening for quite a while, but the VM widget never appears.

**Comment by marmarek** [comment]
@Geblaat qubes-desktop-linux-manager-4.0.17 should fix it.

**Comment by Geblaat** [comment]
> @Geblaat qubes-desktop-linux-manager-4.0.17 should fix it.

Confirmed! Thanks!

**Comment by andrewdavidwong** [comment]
Reopening because the VM list has become too small again with today's updates (only shows 4-5 VMs).

**Comment by marmarta** [comment]
Noooooooooooooooooooooooo ;( 
Okay, back to debugging this monster.

**Comment by andrewdavidwong** [comment]
Not sure what happened, but, after rebooting, suddenly my Qube Manager list is no longer limited to 4-5 VMs, even though I haven't installed any dom0 updates since 2019-10-06.

**Comment by quantumpacket** [comment]
I'm still experiencing this issue with latest dom0 updates and a fresh reboot.

**Comment by quantumpacket** [comment]
I ran the above update and rebooted and the menu is still being wonky.

What is the max height for the menu set as? The scroll should never appear until the height of the screen is reached. A perfect example is how a browser bookmarks menu will keep getting longer and only when it maxes out does it start to scroll. I shouldn't have to scroll when only 6 qubes are running. :\

**Comment by marmarta** [comment]
There's no max height; the problem is that Gtk has a bug with re-drawing the menu when something gets added. It occurs only when the panel with the widget is at the bottom of the screen. All fixes here are basically attempts to somehow work around that bug - there's nothing like a max height set.

**Comment by quantumpacket** [comment]
@marmarek Thanks for the info. Is there a GTK bug report open for this that I could follow?

**Comment by qwrd** [comment]
I recently noticed this on my 4.0-rc2 and was just about to file a report when I found this issue. Basically I haven't noticed the menu get smaller, but I did notice it stay the same size where it should have expanded after starting a new qube or two, resulting in item overflow and the up/down scroll arrows appearing on the menu.

Oddly, if you keep clicking the tray icon to open and close the menu it will eventually grow to full size.

**Comment by marmarta** [comment]
The workaround that works for me (until I maybe finally find a way to work around this that is neither super slow [like the previous approach] nor not actually working) is keeping the panel on top of the screen (or on either side). It breaks (at least from what I've seen) only when the panel is on the bottom.

**Comment by andrewdavidwong** [comment]
Is anyone still experiencing this problem? @qwrd, @quantumpacket, @Zrubi

**Comment by quantumpacket** [comment]
This was fixed for me.

**Comment by andrewdavidwong** [comment]
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.

**Comment by marmarek** [comment]
## Observation

openQA test in scenario qubesos-4.1-pull-requests-x86_64-system_tests_gui_tools@64bit fails in
[qui_widgets_domains](https://openqa.qubes-os.org/tests/17915/modules/qui_widgets_domains/steps/6)

Scrollbar appeared in domains widget. The widget is in default configuration - on top of the screen.

## Test suite description



## Reproducible

Fails since (at least) Build [2021052503-4.1](https://openqa.qubes-os.org/tests/17915) (current job)


## Expected result

Last good: [2021052411-4.1](https://openqa.qubes-os.org/tests/17887) (or more recent)


## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=pull-requests&machine=64bit&test=system_tests_gui_tools&version=4.1)
