### ISSUE TITLE
template reinstall not ported to Qubes 4.0

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3169]
#### Qubes OS version (e.g., `R3.2`): R4.0

---

### Steps to reproduce the behavior:

`sudo qubes-dom0-update --action=reinstall qubes-template-fedora-25`

### Expected behavior:

Template got reinstalled. This include preserving its properties. Technically, only root volume should be overwritten, and private volume should be cleaned.

### Actual behavior:

```
qvm-prefs: error: no such property: 'root_img'
```

And generally the code heavily depends on root.img being a file, and rpm replacing it.

**Comment by 3hhh** [comment]
In general it would be nice to be able re-install or downgrade packages in dom0.

**Comment by tasket** [comment]
I'm installing R4 tonight and will look into this.

**Comment by tasket** [comment]
I'll be trying a fix hopefully this week.

**Comment by tasket** [comment]
Aspects of this issue that need to be addressed:

1. Should not try to delete template on `import_data` failure when template already existed. Easily addressed in qvm_template_postprocess.py
2. Resizing of root volume fails when the existing one had been expanded past the default size. Possibly a security as well as functional issue. Probably there should be a qubesd function that can initialize or zero-out a volume and make this accessible from qubesadmin. Or maybe volume should be deleted and re-created on each import, but I'm not sure where to put this.

**Comment by marmarek** [comment]
@tasket the second point is already tracked here: https://github.com/QubesOS/qubes-issues/issues/2256#issuecomment-345953267

**Comment by marmarek** [comment]
And should be addressed by https://github.com/QubesOS/qubes-core-admin/pull/203 - import is performed on _fresh_ temporary volume, renamed to final name only when finished.

I'm also going to relax anti-shrink protection - move it to qvm-volume tool (GUI settings already prevent it) and allow to do that at API level (and with some option to qvm-volume, probably `--force`). This way, it will be possible to reinstall template and really have it in initial state.

**Comment by tasket** [comment]
Thanks. This is pretty extensive.

The direction I was going was only to remove and re-create the volume in lvm.py. But I was having trouble tracking the call paths from the admin code to qubesd  `import_data()` so that the size of the new data set could be passed to it.

BTW - The `reflink.py` handler appears to deal with import volume safety already, but `file.py` does not.

**Comment by marmarek** [comment]
> Thanks. This is pretty extensive.

Yes. This ticket is not the only reason for it (actually, importing into temporary volume could be done without all the other changes). Other thing is commit operation required multiple steps, which, if something goes wrong, can lead to data loss, or at least need for manual recovery. Extreme result was #3164.
I think the scheme I've finally implemented was proposed by @jpouellet about that time, but I can't find the reference right now.

**Comment by rustybird** [comment]
> I'm also going to relax anti-shrink protection - move it to qvm-volume tool (GUI settings already prevent it) and allow to do that at API level (and with some option to qvm-volume, probably `--force`).

AFAICT we could even make shrinking safe enough for the GUI, by doing the operations in reverse order. Growing a volume is currently

1. dom0 driver: resize backing storage              
2. dom0 driver: resize view of backing storage (e.g. loop devices), if applicable
3. VM: resize partition/device-mapper table entry, if applicable
4. VM: resize filesystem

Shrinking would be 4, 3, 2, 1.

**Comment by marmarek** [comment]
Problem with point 4 is that for most filesystems it can't be done while the filesystem is mounted (in contrary to extending). And for some it isn't supported at all (xfs, but in practice we care about ext4 only). This is definitely doable (for example from initramfs), but not just "doing the operations in reverse order".

BTW currently we recommend universal method for shrinking, by creating new smaller VM and moving data: https://www.qubes-os.org/doc/resize-disk-image/#shrinking-a-disk-image

**Comment by rustybird** [comment]
> Problem with point 4 is that for most filesystems it can't be done while the filesystem is mounted (in contrary to extending).

Damn, I never noticed that restriction in the `resize2fs` manpage. Too bad then.

**Comment by marmarek** [comment]
> BTW - The reflink.py handler appears to deal with import volume safety already, but file.py does not.

Fixed here: https://github.com/marmarek/qubes-core-admin/commit/f870272b081c4f776f8e40b2a4942dce7f410d6a (https://github.com/QubesOS/qubes-core-admin/pull/206)

**Comment by tasket** [comment]
I think we still have a problem with resizing during import, if new image is smaller:

https://github.com/QubesOS/qubes-core-admin/blob/e2b70306e558face4003b3e42e3dcedd6f31949f/qubes/api/admin.py#L470-L472

```
 def import_root_img(vm, source_dir):
     '''Import root.img into VM object'''
 
 
     root_size = get_root_img_size(source_dir)
     vm.volumes['root'].resize(root_size)
```

Won't an error get raised in lvm.py resize()  `if size < self.size` ?
```
        if size < self.size:
            raise qubes.storage.StoragePoolException(
                'For your own safety, shrinking of %s is'
                ' disabled (%d < %d). If you really know what you'
                ' are doing, use `lvresize` on %s manually.' %
                (self.name, size, self.size, self.vid))


        if size == self.size:
            return


        if self.is_dirty():
            cmd = ['extend', self._vid_snap, str(size)]
            qubes_lvm(cmd, self.log)
        elif hasattr(self, '_vid_import') and \
```

**Comment by marmarek** [comment]
You're right, working on it.

**Comment by tasket** [comment]
Also, is the new image size being propagated to (lvm|reflink|file).py `import_data()` when that function is called? I can't tell.

**Comment by marmarek** [comment]
That's why qvm-template-postprocess calls volume.resize first.

**Comment by tasket** [comment]
I see, the size attribute gets set without doing lvextend/truncate. Makes sense now.

**Comment by tasket** [comment]
PR https://github.com/QubesOS/qubes-core-admin-client/pull/61

**Comment by awokd** [comment]
Verified to fix the missing directory after a reinstall. Thank you!
