### ISSUE TITLE
Lenovo x230t : BackSpace keycode (c:160) is mapped to XF86ScreenSaver, not BackSpace

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#3306]
#### Qubes OS version:

R3.2, R4.0rc1, R4.0rc2

#### Affected TemplateVMs: 

dom0 fedora-23, dom0 fedora-25

---

### Steps to reproduce the behavior:

Install Qubes 3.2. At login prompt, backspace doesn't do its backspace function anymore.  

### Expected behavior:

Under x230t (not true for x230!?) doing `sudo xev` key shows that it's mapped to BackSpace

### Actual behavior:

`sudo xev` and typing the backspace key shows that it's linked to XF86ScreenSaver, not BackSpace

### General notes:

Corrective action is to add the following line in the file `/etc/X11/Xmodmap`:
`keycode 160 = BackSpace NoSymbol BackSpace`

---

**Comment by tlaurion** [comment]
Doesn't resolve the issue after reboot. What the hell?

**Comment by marmarek** [comment]
I guess `/etc/X11/Xmodmap` isn't loaded by lightdm...

**Comment by marmarek** [comment]
Does it work correctly on plain Fedora 25 (or newer)?

**Comment by tlaurion** [comment]
Overwriting /etc/X11/Xmodmap with the following file makes the change persistent over 4.0 rc3, effective from dom0 and launched qubes.

[xmodmap_x230t.txt](https://github.com/QubesOS/qubes-issues/files/1657644/xmodmap_x230t.txt)

**Comment by tlaurion** [comment]
My x230t is dead. Cannot test this but for anyone else with the same problem:

forums.puri.sm/t/keyboard-layout-unable-to-recognize-pipe/2022

**Comment by tlaurion** [comment]
My x230t is dead. Cannot test this but for anyone else with the same kind of problem:

forums.puri.sm/t/keyboard-layout-unable-to-recognize-pipe/2022

**Comment by tlaurion** [comment]
My x230t is dead. Cannot test this but for anyone else with the same kind of problem:

forums.puri.sm/t/keyboard-layout-unable-to-recognize-pipe/2022

**Comment by tlaurion** [comment]
X230t resuscitated.

modalias content: 
`dmi:bvncoreboot:bvrCBET4000heads:bd01/01/1970:svnLENOVO:pn343727U:pvrThinkPadX230Tablet:rvnLENOVO:rn343727U:rvrThinkPadX230Tablet:cvnLENOVO:ct9:cvr: `

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.

**Comment by matthewspangler** [comment]
I had this same issue on a Thinkpad x230T running coreboot/heads-maximized-hotp with Qubes OS 4.1.

Both the 'Backspace' and '| \' keys were unresponsive, not functioning at all.

For me the solution was editing `/usr/lib/udev/hwdb.d/60-keyboard.hwdb` in dom0 like so:

1) Find the line containing: `Thinkpad*X2*Tablet*` (for me it was around line 963)
2) Add `:rvn*` to the end of the line, like so:
`evdev:atkbd:dmi:bvn*:bvr*:bd*:svnLENOVO*:pn*:pvrThinkPad*X2*T*:rvn*`

This systemd PR demonstrates this fix: https://github.com/systemd/systemd/pull/27211/commits/3bbdb329be75bcdf2902720b36b8feb94e955b49#diff-df937b870825d805803c76ae8258342dcd6850770f4404721e044af93ac3d231R963

**Comment by matthewspangler** [comment]
I can confirm I am having this issue on a Thinkpad X320T running Qubes 4.1.2 with the following version of Heads: heads-x230-hotp-maximized-v0.2.0-1577-g91f65be-bottom

Not only does backspace not work, the '| \' key (underneath backspace) does not work either.

**Comment by matthewspangler** [comment]
I can confirm I am having this issue on the following setup:

Thinkpad X230T
Qubes OS 4.1.2
Heads-x230-hotp-maximized-v0.2.0-1577-g91f65be 
- https://app.circleci.com/pipelines/github/osresearch/heads/612/workflows/87b50d50-6afd-46bc-9130-7475bb9fc1ee/jobs/10337/artifacts

Both the 'Backspace' and '| \' keys are not unresponsive, not functioning at all.

I have tried the following fix detailed in these two links:
- https://github.com/osresearch/heads/issues/958#issuecomment-1530639642
- systemd/systemd@3bbdb32#diff-df937b870825d805803c76ae8258342dcd6850770f4404721e044af93ac3d231R963

Here are the steps for this fix:
1) Edit /usr/lib/udev/hwdb.d/60-keyboard.hwdb in dom0
2) Find the line containing: Thinkpad*X2*Tablet* (for me it was around line 963)
3) Add :rvn* to the end of the line, like so: `evdev:atkbd:dmi:bvn*:bvr*:bd*:svnLENOVO*:pn*:pvrThinkPad*X2*T*:rvn*`
This issue is related to systemd and has been patched in this PR:

After this fix, both keys work *most* of the time, but occassionally I will find in the middle of my daily usage that they're not working again. Usually a reboot takes care of this. I am still trying to replicate the intermittent regression.

**Comment by matthewspangler** [comment]
I can confirm I am having this issue on the following setup:

Thinkpad X230T
Qubes OS 4.1.2
Heads-x230-hotp-maximized-v0.2.0-1577-g91f65be 
- https://app.circleci.com/pipelines/github/osresearch/heads/612/workflows/87b50d50-6afd-46bc-9130-7475bb9fc1ee/jobs/10337/artifacts

Both the 'Backspace' and `| \\` keys are not unresponsive, not functioning at all.

I have tried the following fix detailed in these two links:
- https://github.com/osresearch/heads/issues/958#issuecomment-1530639642
- systemd/systemd@3bbdb32#diff-df937b870825d805803c76ae8258342dcd6850770f4404721e044af93ac3d231R963

Here are the steps for this fix:
1) Edit `/usr/lib/udev/hwdb.d/60-keyboard.hwdb` in dom0
2) Find the line containing: `Thinkpad*X2*Tablet*` (for me it was around line 963)
3) Add :rvn* to the end of the line, like so: `evdev:atkbd:dmi:bvn*:bvr*:bd*:svnLENOVO*:pn*:pvrThinkPad*X2*T*:rvn*`
This issue is related to systemd and has been patched in this PR:

After this fix the keys work, but I will sometimes experience regression--sometimes one key, sometimes both. I am still trying to replicate the scenarios where either stops working.

**Comment by matthewspangler** [comment]
I have an update on this issue. The inconsistency of this bug presenting is related to whether the Heads is cold booted vs. rebooted to from Qubes OS. If I reboot from Qubes OS, backspace works. If I cold boot Heads with the x230 power button, backspace is broken.

See this comment here: 
https://github.com/linuxboot/heads/pull/1525#issuecomment-1810802483

**Comment by matthewspangler** [comment]
I've figured out why this bug sometimes appears for me, and sometimes doesn't. 

Bug appears when:
1) Do a cold boot. Unplug battery, unplug power cable, hold power button to drain power
2) Type LUKS password -- at this point, backspace and "| \" work in the LUKS text box
3) User login -- at this point, backspace and "| \" have stopped working, and continue to not work after login.

Bug doesn't appear when:
1) Do warm boot by rebooting from Qubes OS. 
2) Keys work fine @ LUKS prompt + user login + desktop.

Looks related to this Heads bug: https://github.com/linuxboot/heads/pull/1525#issuecomment-1810802483

**Comment by toothlesslizard** [comment]
Same  on Qubes 4.2 and x230 from xytech (keyboard from x220).
backspace, /, |   this keys work intermittently 
I have Ubuntu on second disk drive and there is no troubles.

Qubes 4.2
FW_VER - Heads-v0.2.0-1796-g35f3b22-dirty
Kernel: Linux 5.10.5 - heads
X230-maximized-eDP

**Comment by tlaurion** [comment]
Somebody reported that using q4.2 changed the behavior. Went extensively
with the user and this happens only on cold boot, where reboot detect the
keyboard correctly.

Curated the logs and opened a PR under heads at
https://github.com/linuxboot/heads/pull/1525 which contains his logs.

The bug is that on cold boot, i8042 probes the keyboard and detects it as
Raw translated 2, where on reboot it's detected correctly as AT translated
2. Unfortunately I do not understand what is happening there. But the logs
have i8042 in debug mode with kernel option to not timeout which is the
best I could come up to gather logs from the user.

No clue what is happening there and cannot replicate on my x230. This is
not a x230t here. Keyboard sku still unknown.

**Comment by toothlesslizard** [comment]
@tlaurion do you need dmesg +sku? this bug not only 230t related

**Comment by tlaurion** [comment]
I wonder if that would fix it under x230 under coreboot 

```
--- a/src/drivers/i8042/i8042.c
+++ b/src/drivers/i8042/i8042.c
@@ -132,7 +132,11 @@ static int i8042_init(void)
 	/* Enable keyboard interface */
 	i8042_command(&param, I8042_CMD_CTL_WCTR);
 
+#if CONFIG_BOARD_LENOVO_X230
+	param |= I8042_XLATE;
+#else
 	param &= ~I8042_XLATE;
+#endif
 	i8042_command(&param, I8042_CMD_CTL_WCTR);
 
 	/* Flush any pending input. */
```

Problem is 

```
--- a/src/drivers/i8042/i8042.h
+++ b/src/drivers/i8042/i8042.h
@@ -23,7 +23,7 @@
 #define I8042_AUX_OBF		0x20	/* output buffer full */
 #define I8042_AUX_IRQ		12
 
-#define I8042_XLATE		0x00	/* translate scan code set 2 to 1 */
+#define I8042_XLATE		0x40	/* translate scan code set 2 to 1 */
 #define I8042_MUX_QUIRK		0x02	/* enable multiplexing quirk */
 
 #define I8042_KBD_IRQ		1
```

**Comment by matthewspangler** [comment]
I'm ignorant as to a lot of this, but I'm going to take a wild guess--I read some PS/2-based integrated keyboards do a brief self-test on cold boot, which means they're not ready on boot. There's a kernel parameter in >=6.7 called "i8042.probe_defer" meant to deal with this. I'm running kernel 6.5 so I'm unable to test this until later.
https://github.com/torvalds/linux/commit/9222ba68c3f4065f6364b99cc641b6b019ef2d42

**Comment by tlaurion** [comment]
Analysis of debug logs at https://github.com/linuxboot/heads/pull/1525#issuecomment-1816501783

**Comment by tlaurion** [comment]
Possible fixes upstream in coreboot
https://github.com/linuxboot/heads/pull/1525#issuecomment-1816554912

Attempting discussion with coreboot developers on chat.

Could also patch coreboot under heads for willing testers under referred PR.

**Comment by tlaurion** [comment]
> I'm ignorant as to a lot of this, but I'm going to take a wild guess--what about kernel option "i8042.probe_defer" in kernels >=6.7? It's related to integrated PS/2 keyboards not being ready at cold boot because they're busy performing a self-test.
> 
> https://github.com/torvalds/linux/commit/9222ba68c3f4065f6364b99cc641b6b019ef2d42
> https://bugs.launchpad.net/ubuntu/+source/linux-source-2.6.17/+bug/76881

I think this would happen too late. My reasoning to push for a detection fix or hardcoding on coreboot side is that Linux should to the right thing if coreboot result was good. At least that's my reasoning which could be faulty.

**Comment by tlaurion** [comment]
I think I fixed it with ugly fix. Needs testing to raise attention from coreboot developers. See https://github.com/linuxboot/heads/pull/1525#issuecomment-1817058361

**Comment by tlaurion** [comment]
Looking at i8042 source, it seems that passing from coreboot config to hawds kernel : `CONFIG_LINUX_COMMAND_LINE="i8042.force=1:kbd"` should actually be enough

**Comment by toothlesslizard** [comment]
strange,  problem persists.
added these lines and rebuild rom. lightdm greeter won't respond to the backspace key.
or iam doing something wrong?
```
user@heads:~/heads/config$ cat coreboot-x230-maximized-fhd_edp.config | grep 8042
CONFIG_LINUX_COMMAND_LINE="intel_iommu=igfx_off i8042.force=1:kbd quiet"
```

**Comment by tlaurion** [comment]
> strange,  problem persists.
> added these lines and rebuild rom. lightdm greeter won't respond to the backspace key.
> or iam doing something wrong?
> ```
> user@heads:~/heads/config$ cat coreboot-x230-maximized-fhd_edp.config | grep 8042
> CONFIG_LINUX_COMMAND_LINE="intel_iommu=igfx_off i8042.force=1:kbd quiet"
> ```
> 
> Qubes grub no effect too.

Well. That doesn't seem enough. 
Can you confirm from dmesg output of 
'sudo dmesg | grep - I keyb`

**Comment by tlaurion** [comment]
@toothlesslizard also if you could deactivate CONFIG_DRIVERS_PS2_KEYBOARD from coreboot config that would make a consistent test without coreboot ps2 init being in the way whatsoever.

behavior should be different between cold boot (power off, holding power 10 seconds) and warm boot (reset, reboot) as for everybody else.

**Comment by toothlesslizard** [comment]
@tlaurion I'm getting different outputs from the shell recovery (on/off laptop) :

```
[          0.828917] input : AT Translated Set 2 keyaboard as /devices/platform/i8042/serio0/input/input3

[DEBUG] Keyboard init ...
[ INFO ] Keyboard controller output buffer result timeout
[DEBUG] PS/2 Keyabord initialized on primary channel 
```
or this

```
[     0.824340] input : AT RAW Set 2 keyboard as /devices/platform/i8042/serio0/input/input3
[     1.692471] input : AT RAW Set 2 keyboard as /devices/platform/i8042/serio0/input/input6

[DEBUG] Keyboard init ...
[ INFO ] Keyboard controller output buffer result timeout
[ INFO ] Keyboard controller output buffer result timeout
[ INFO ] Keyboard controller output buffer result timeout
[ERROR] Keyboard reset failed ASK: 0xaa
```

**Comment by toothlesslizard** [comment]
full output from Qubes OS. cant filtering cause keys not working.
[full-dmesg.txt](https://github.com/QubesOS/qubes-issues/files/13401230/full-dmesg.txt)

**Comment by tlaurion** [comment]
> new rom from scratch\nCBET4000 Heads-v0.2.0-1914-g1f39d16-dirty\nstock bios from here : https://github.com/xy-tech/x330-bios/tree/main/stock/original\n\nuser@heads:~/heads/config$ cat coreboot-x230-maximized-fhd_edp.config | grep -i \"8042\"\nCONFIG_LINUX_COMMAND_LINE=\"intel_iommu=igfx_off i8042.force=1:kbd quiet loglevel=2\"\nuser@heads:~/heads/config$ cat coreboot-x230-maximized-fhd_edp.config | grep -i \"KEYBO\"\n# CONFIG_DRIVERS_PS2_KEYBOARD is not set\ncbmem | grep keyb or Keyboa - no outut now.\nother things about AT Translated / AT RAW same. See prev post.\n\nIf anyone interesting i have different sku keyboards. But swapping not help.



I'm sorry @toothlesslizard i didn't get that part.

 Are you saying that on stock bios (x330 referenced) you are getting the same coldboot=raw, reboot/warm reset=at?

**Comment by toothlesslizard** [comment]
No, I just added details about the firmware build, nothing more. 
The point is, the keys continue to malfunction.
Only cold boot.  Recovey shell and LUKS - good, LightDM Greeter - keys fall off.

**Comment by tlaurion** [comment]
> Boot from second drive and output from Ubuntu (keys works good)

The Raw Translated being dealt with Ubuntu is nice but is what differenciate quebesos from others here.


Raw Translated 2 should not happen. We want AT Translated 2, otherwise we have different behaviors across OSes because of workarounds applied differently accros OSes. If AT translated 2: no problem across all OSes.


The question is how to arrive with that. With hacks on coreboot disabling exit 0 on patch referred above, we arrive to that state but that is really ugly.

So this is where we are here. No real progress knowing which kernel parameters need to be set so that if firmware doesn't get in the way, we get to AT translated 2, otherwise OSes have to apply quirks of their own. Which won't work if ps2 protocol switches between AT translated 2 to Raw Translated 2. I hope we are now clear on what the problem is if we haven't found proper solution... Yet.

**Comment by tlaurion** [comment]
Opened issue https://ticket.coreboot.org/issues/515

**Comment by ben-grande** [comment]
@tlaurion Can this be closed? It is not a Qubes issue and it was filed to coreboot: https://ticket.coreboot.org/issues/515. You also stopped support X230t: https://github.com/linuxboot/heads/issues/1744#issuecomment-2480002209

**Comment by ben-grande** [comment]
Closing as upstream issue.
