### ISSUE TITLE
aptitude is not working in Whonix VMs

### ISSUE THREAD

**Issue by starius** [QubesOS/qubes-issues#3882]
### Qubes OS version:

`R4.0`

### Affected component(s): 

Whonix

---

### Steps to reproduce the behavior:

Open Konsole in `whonix-gw` or `whonix-ws` and type `sudo aptitude update`

### Expected behavior:

I expect the command to work.

### Actual behavior:

The command fails.

![whonix-aptitude](https://user-images.githubusercontent.com/920155/39667306-fa413e16-5080-11e8-8e55-b0487641021f.png)

At the same time, `apt-get` works in Whonix. Also, on Debian both `apt-get` and `aptitude` work.

**Comment by marmarek** [comment]
@adrelanos ?

**Comment by adrelanos** [comment]
Maybe uwt issue.

https://github.com/Whonix/qubes-whonix/blob/master/etc/uwt.d/40_qubes.conf#L70

What if you run `sudo aptitude-curses update` directly, does that work?

```
~ $ ls -la /usr/bin/aptitude
lrwxrwxrwx 1 root root 26 Aug  9  2016 /usr/bin/aptitude -> /etc/alternatives/aptitude

~ $ ls -la /etc/alternatives/aptitude
lrwxrwxrwx 1 root root 24 Aug  9  2016 /etc/alternatives/aptitude -> /usr/bin/aptitude-curses
```

Looks same for you?

**Comment by starius** [comment]
> What if you run sudo aptitude-curses update directly, does that work?

No, I see the same errors:

```
W: Failed to fetch http://security.debian.org/dists/jessie/updates/contrib/binary-amd64/Packages:
Cannot initiate the connection to 127.0.0.1:8082 (127.0.0.1). - connect (1: Operation not permitted)
```

> Looks same for you?

Yes.

I did not change anything in Whonix templates - it happened right after installation of Qubes 4.

**Comment by adrelanos** [comment]
Note to self: works in Qubes-Whonix 14 / Qubes R3.2

**Comment by adrelanos** [comment]
This is fixed in Qubes-Whonix 14 after upgrades. Please test.

**Comment by starius** [comment]
I upgraded everything using Qube Manager and restarted the VM. Still getting that error.
How to check the Whonix version I am using?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Whonix
Description:    Whonix GNU/Linux 8.10 (jessie)
Release:        8.10
Codename:       jessie
```

**Comment by adrelanos** [comment]
Expected. You're on stable rather than testers-only version. Fixed inQubes-Whonix 14 after upgrades only.

**Comment by adrelanos** [comment]
Fixed in Whonix 14.

Close please.
