### ISSUE TITLE
Can't open Debian terminal from gui, but can from dom0 terminal 

### ISSUE THREAD

**Issue by e6lk7dqzm83p** [QubesOS/qubes-issues#4344]
### Qubes OS version:

4.0

### Affected component(s): 

Debian terminal

---

### Steps to reproduce the behavior:

When I try to open up a terminal in my Debian AppVM via the Qubes Domain agent (the Q in the task bar) by going to DebianAppVM -> terminal a terminal does not open.  The terminal opens when called from dom0 (i.e. `qvm-run -a DebianAppVM gnome-terminal`).

### Expected behavior:

The terminal in my DebianAppVM opens when selected from the GUI.

### Actual behavior:

The terminal in my DebianAppVM does not open when selected from the GUI.

### General notes:

---

**Comment by andrewdavidwong** [comment]
Similar to (possible duplicate or regression of): #3533, #3433, #3473.

**Comment by unman** [comment]
I believe that this issue is fixed in qubes-core-agent 4.0.36-1 package.

@e6lk7dqzm83p Can you confirm that an update resolves the problem please?

**Comment by e6lk7dqzm83p** [comment]
Sorry @unman, this fell through my Inbox.

I have the latest updates (running `sudo qubes-dom0-update` yields "No new updates available") and this problem persists.  

Is there another command I should run to get the latest qubes-core-agent?  How do I check which version I'm running?

Thank you!

**Comment by unman** [comment]
@e6lk7dqzm83p If I take a clean template I see the behavior you describe.
Upgrading qubes-core-agent **in the template** to 4.0.37-1 resolves the problem. (Just updating that package on its own is sufficient.)
Can you check that?

**Comment by e6lk7dqzm83p** [comment]
Hi @unman, that fixed the issue. I hadn't installed qubes-core-agent, sorry to have wasted your time :-/

**Comment by andrewdavidwong** [comment]
Closing this as "resolved." If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.
