### ISSUE TITLE
keyboard layout propagation from dom0 to VM recently broken

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4489]
### Qubes OS version:
R4

### Affected component(s): 
whonix-gw-14, whonix-ws-14, anon-whonix, sys-whonix

Possibly not Whonix specific. Possibly newly build Debian templates are also affected?

### Steps to reproduce the behavior:

Install testers-only version `Qubes-Whonix 14 (4.0.1-201811040215) TemplateVMs Point Release for Qubes R4`.

* https://forums.whonix.org/t/qubes-whonix-14-4-0-1-201811040215-templatevms-point-release-for-qubes-r4-testers-wanted/6252
* https://www.whonix.org/wiki/Qubes/Install/Testing
* https://github.com/QubesOS/updates-status/issues/781
* https://github.com/QubesOS/updates-status/issues/783

Start any Whonix VM and try typing.

### Expected behavior:
Using local VM keyboard layout same as dom0 keyboard (de-DE) layout as before for Whonix 14 version in Qubes community repository (stable). Also same as for all other templates.

### Actual behavior:
Using en-US keyboard layout.

### General notes:
No changes in any Whonix code that would be affecting this to my knowledge.

### Related issues:
* https://forums.whonix.org/t/cannot-change-qubes-keyboard-layout/6259
* https://github.com/QubesOS/qubes-issues/issues/1396

**Comment by adrelanos** [comment]
sys-whonix

```
qubesdb-multiread / | grep -i key
qubes-keyboard = xkb_keymap {\x0a\x09xkb_keycodes  { include "evdev+aliases(qwertz)"\x09};\x0a\x09xkb_types     { include "complete"\x09};\x0a\x09xkb_compat    { include "complete"\x09};\x0a\x09xkb_symbols   { include "pc+de+inet(evdev)"\x09};\x0a\x09xkb_geometry  { include "pc(pc105)"\x09};\x0a};
```

debian-9 based AppVM

```
qubesdb-multiread / | grep -i key
qubes-keyboard = xkb_keymap {\x0a\x09xkb_keycodes  { include "evdev+aliases(qwertz)"\x09};\x0a\x09xkb_types     { include "complete"\x09};\x0a\x09xkb_compat    { include "complete"\x09};\x0a\x09xkb_symbols   { include "pc+de+inet(evdev)"\x09};\x0a\x09xkb_geometry  { include "pc(pc105)"\x09};\x0a};
```

Same.

**Comment by marmarek** [comment]
Fixed already while fixing #4434: https://github.com/QubesOS/qubes-gui-agent-linux/commit/e9b972e44c9cea5021067fd66462f61314e7620a

**Comment by adrelanos** [comment]
As per git it looks like `qubes-gui-agent` `4.0.18` does not fix it.

I guess I have to wait for `qubes-gui-agent` `4.0.19`.

Would it be appropriate to (re-)open some ticket to serve as reminder to build `qubes-gui-agent` `4.0.19` or is this already in the list somewhere?

**Comment by ryan-green** [comment]
sorry for the dup (just found this) #791

**Comment by ryan-green** [comment]
As a quick related note, after adding a script to /etp/profile.d/ the different ways to launch a terminal differ in their results:
* xfce menu -- correct
* qvm-run -a appvm app -- correct
* "Run command in qube" from the Qube Manager -- produces wrong keyboard if launching from a currently halted VM, but for a currently running appvm it produces correct keyboard config. 

Perhaps there is an artifact added by the qubes-manager... a small separate issue perhaps.

**Comment by adrelanos** [comment]
Is now in Qubes testing.

https://github.com/QubesOS/updates-status/issues/799

**Comment by adrelanos** [comment]
No more issue on Qubes-Whonix template building side. Yay! :) Builds

* https://github.com/QubesOS/updates-status/issues/806
* https://github.com/QubesOS/updates-status/issues/807

were ok.

**Comment by GammaSQ** [comment]
It's unclear to me how I would fix this issue on an existing installation.
I believe I have to enable a testing-repository in debian/whonix templates. Is this done via Salt or within the template? I was unable to find documentation on this.
Or do I have to reinstall the templates?

**Comment by unman** [comment]
You can do this in the template - it's standard Debian use, not Qubes specific. Probably easier not to use salt for this.

Edit the file` /etc/apt/sources.list.d/qubes-r4.list` - you'll see the entries for `update candidate repositories `are commented out. 
Remove the '#' from the relevant line.
Then update the package list and install packages as required.
If you want to, you can disable the testing repo immediately after - dont forget to update the available packages again.
