### ISSUE TITLE
can't persistently attach mic

### ISSUE THREAD

**Issue by GammaSQ** [QubesOS/qubes-issues#4718]
### Affected component(s): qvm-device mic

---

### Steps to reproduce the behavior:

(work is a fedora-29 VM and is shut down)
`qvm-device mic a --peristent work dom0:mic`

### Expected behavior:

no error, start work, mic is attached.

### Actual behavior:

Error:
`Failed to attach microphone: pulseaudio agent not running in work`
starting work does not attach mic automatically.
(other attach-commands work, though!)

---

### Related issues:

https://github.com/QubesOS/qubes-issues/issues/4054

**Comment by andrewdavidwong** [comment]
> `Failed to attach microphone: pulseaudio agent not running in work`

In my experience, this error happens only when I try to attach a mic to a VM based on a more minimal template. When I instead try to attach to a VM based on a "full" template, it works.

**Comment by marmarek** [comment]
it needs `pulseaudio-qubes` package installed.

**Comment by andrewdavidwong** [comment]
@GammaSQ, can you verify whether the `pulseaudio-qubes` package is installed in the VMs in which you encounter this problem?

**Comment by GammaSQ** [comment]
This happens when the VM (work) is powered down.
If the VM is running when the mic is attached, everything works fine. However, since `--persistent` is used, this is not the expected behavior.

Additionally, as I just found out, the persistent mic can't be detached anymore.

    [starting w. VM 'work' powered down]
    $ qvm-device mic d work dom0:mic
    Fialed to attach microphone: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.qubesos.Audio.work was not provided by any .service files (2)
    $ qvm-start work
    $ qvm-device mic d work dom0:mic
    Can not remove a persistent attachment from a non halted vm

Interestingly, the first error complains about failing to _attach_ the microphone.

**Comment by daktak** [comment]
I have the exact issue as I've persistently attached the mic. Will I be able to attach to another VM if i shutdown, rename or delete the persistent VM?

**Comment by daktak** [comment]
Resolved by editing xml as described by @nil0x42 in #4054

**Comment by SaswatPadhi** [comment]
This issue still persists in R4.1 -- I get the same error on trying to attach persistently

**Comment by andrewdavidwong** [comment]
Did you check this? https://github.com/QubesOS/qubes-issues/issues/4718#issuecomment-549127709

**Comment by SaswatPadhi** [comment]
Yes, I tried with `pulseaudio-qubes` is installed, but the VM was not running (which should still work for the `--persistent` option).

**Comment by ben-grande** [comment]
@andrewdavidwong Yes! Affects R4.2.

**Comment by ben-grande** [comment]
My comment here https://github.com/QubesOS/qubes-issues/issues/4718#issuecomment-2693674269 should have been another issue. I probably commented on another issue, but it is not linked here and can't remember. Closing as solved.
