### ISSUE TITLE
qubes-snapd-helper package missing from standard Fedora repo

### ISSUE THREAD

**Issue by daniel-ayers** [QubesOS/qubes-issues#4811]
### Qubes OS version:

R4.0.1

### Affected component(s):

qubes-snapd-helper package

### Expected behavior:

On Fedora 28:

```
$ dnf repolist
repo id                                                                        repo name                                                                                     status
*fedora                                                                        Fedora 28 - x86_64                                                                            57,327
qubes-vm-r4.0-current                                                          Qubes OS Repository for VM (updates)                                                             682
*updates                                                                       Fedora 28 - x86_64 - Updates                                                                  21,147
$ sudo dnf search qubes-snapd-helper
Last metadata expiration check: 1 day, 0:55:36 ago on Mon 11 Feb 2019 12:54:41 PM NZDT.
==================================================================== Name Exactly Matched: qubes-snapd-helper =====================================================================
qubes-snapd-helper.noarch : Helper for snapd to make snaps persistent in Qubes VMs
qubes-snapd-helper.src : Helper for snapd to make snaps persistent in Qubes VMs
$ dnf whatprovides /usr/lib/systemd/system/qubes-snapd-mount.service
Last metadata expiration check: 0:01:29 ago on Tue 12 Feb 2019 01:49:18 PM NZDT.
qubes-snapd-helper-1.0.0-1.fc28.noarch : Helper for snapd to make snaps persistent in Qubes VMs
Repo        : @System
Matched from:
Filename    : /usr/lib/systemd/system/qubes-snapd-mount.service

qubes-snapd-helper-1.0.0-1.fc28.noarch : Helper for snapd to make snaps persistent in Qubes VMs
Repo        : qubes-vm-r4.0-current
Matched from:
Filename    : /usr/lib/systemd/system/qubes-snapd-mount.service
```

### Actual behavior:

On Fedora 29 VM:

```
$ dnf repolist
repo id                                                                        repo name                                                                                     status
*fedora                                                                        Fedora 29 - x86_64                                                                            58207
*fedora-modular                                                                Fedora Modular 29 - x86_64                                                                        8
qubes-vm-r4.0-current                                                          Qubes OS Repository for VM (updates)                                                            329
*updates                                                                       Fedora 29 - x86_64 - Updates                                                                  16953
*updates-modular                                                               Fedora Modular 29 - x86_64 - Updates                                                              8
$ sudo dnf search qubes-snapd-helper
Last metadata expiration check: 0:02:08 ago on Tue Feb 12 13:48:21 2019.
No matches found.
$ dnf whatprovides /usr/lib/systemd/system/qubes-snapd-mount.service
Last metadata expiration check: 0:00:45 ago on Tue Feb 12 13:49:56 2019.
Error: No Matches found
```

**Comment by daniel-ayers** [comment]
According to https://github.com/QubesOS/updates-status/issues/684 the package has been deployed to the testing repo for FC29.  Given it exists in the stable repo for FC28, perhaps it should also be in the stable repo for FC29?

**Comment by marmarek** [comment]
The package was uploaded to fc29 testing _after_ moving it to stable for fc28 - which caused this problem. I've triggered stable upload again, so it should be fixed in few minutes.

**Comment by daniel-ayers** [comment]
Thank you, as always. :)

**Comment by cgchinicz** [comment]
Hi, it seems the issue is back. Can you check it? Thanks in advance

**Comment by marmarek** [comment]
On which exactly template? I've just checked on Fedora 29 and it is there.
On other supported templates on R4.0 it also seems to be present, at least according to https://ftp.qubes-os.org/~qubesosbot/status.html

**Comment by hanetzer** [comment]
Not sure if this is an apropriate place to report, but qubes-snapd-helper is also missing for fedora-32 templatevms in the 4.1 alpha (needed because older didn't support my hw)

**Comment by andrewdavidwong** [comment]
> Not sure if this is an apropriate place to report, but qubes-snapd-helper is also missing for fedora-32 templatevms in the 4.1 alpha (needed because older didn't support my hw)

Is it missing from the template or from the repo?

**Comment by hanetzer** [comment]
both, template doesn't come with it, and attempting to install it gives me a not found error.
