### ISSUE TITLE
Qube Devices no longer populates 

### ISSUE THREAD

**Issue by farrilis** [QubesOS/qubes-issues#4915]
### Qubes OS version:
R4.0

### Affected component(s) or functionality:
Qubes Devices tray drop-down

---

### Steps to reproduce the behavior:

Update to latest `qubes-usb-proxy` (or something related) 

### Expected or desired behavior:

All PCI, SATA and USB based devices appear in Qubes Devices drop-down

### Actual behavior:

Qubes Devices drop down contains only sdx SATA devices. The USB hub is now missing, and no USB devices appear when inserted (SD cards are a part of the USB device on this hardware, I believe). Camera (internal device) is also absent.

Plugging in a USB device generates the usual notification message. 

### General notes:

Starting sys-usb produces the usual notifications about internal devices connected to sys-usb (e.g. camera, which is an internal device). Inserting USB devices or SD cards, also generates expected notifications. Only the drop-down menu for qube assigning is dysfunctional

Using unmodified Debian 9 template for sys-usb qube 

Hardware:   Purism Librem 13v3

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):

Used the manual sys-usb guide in Qubes Docs to create the sys-usb (several months ago). Was working until last 2 updates (a previous qubes update broke ability to unassign device in Qubes Devices)

**Comment by farrilis** [comment]
`lspci` still lists PCI bridge and USB controller (which are missing from Qubes Devices drop-down). Internal devices e.g. soundcard continue to work

`qvm-block attach myqube sys-usb:1-2` generates this error
qvm-block: error: backend vm 'sys-usb' doesn't expose device '1-2'

**Comment by marmarek** [comment]
Devices widget do not include (and never had) PCI devices on purpose. Those are rarely hot pluggable, and generally shouldn't be switched between VMs at runtime.

> The USB hub is now missing

USB hub itself should also _not_ be listed in the widget (or `qvm-usb`). If it ever was (which I doubt), it was a bug. There should be only devices connected to that hub.

> `qvm-block attach myqube sys-usb:1-2` generates this error
> qvm-block: error: backend vm 'sys-usb' doesn't expose device '1-2'

`qvm-block` can attach block devices (listed by `qvm-block`). This one looks like the whole USB device (not block device being part of it). 

See: https://www.qubes-os.org/doc/usb/

Since multiple points above looks like misunderstanding, not actually a bug, lets do some test:
1. Open devices widget and see what devices are there.
2. Close it.
3. Plug in some USB stick.
4. Open devices widget again

Now you should see additional block device (like `sys-usb:sda`) and an USB device (like `sys-usb:3-2`).
Is it there, or some of it is missing?
Then, check if `qvm-block` and `qvm-usb` include those devices.


You may also want to install an [qubes-desktop-linux-manger 4.0.17](https://github.com/QubesOS/updates-status/issues/987) update from current-testing repository - it contains multiple fixes for devices widget.

**Comment by farrilis** [comment]
@marmarek, 

>  1. Open devices widget and see what devices are there.

dom0 SATA disk/partitions only

>  2. Close it.
>  3. Plug in some USB stick.
>  4. Open devices widget again

still dom0 SATA disk/partitions

> Then, check if `qvm-block` and `qvm-usb` include those devices.

`qvm-usb list` shows all USB devices connected to the ports. Running `qvm-block attach sys-usb:2-2` generates the same error message:

qvm-block: error: backend vm 'sys-usb' doesn't expose device '2-2'


I (wrongly) assumed the camera was connected internally with PCI, running `qvm-usb list` proves the camera is a USB device, and not PCI

**Comment by marmarek** [comment]
> qvm-block: error: backend vm 'sys-usb' doesn't expose device '2-2'

Please read my comment above again.

**Comment by marmarek** [comment]
> still dom0 SATA disk/partitions

This sounds like an issue already fixed in qubes-desktop-linux-manager 4.0.17. What version do you have? (check with `rpm -q  qubes-desktop-linux-manager`)
See [here](https://www.qubes-os.org/doc/software-update-dom0/#testing-repositories) how to install packages from current-testing.

**Comment by farrilis** [comment]
I tried `qubes-dom0-update --enable-repo=qubes-dom0-current-testing --action=upgrade qubes-desktop-linux-manger`, 4.0.17-1.fc25 now installed. 

Situation is unchanged, SATA devices only in Qubes Devices widget. `qvm-usb list` correctly lists available USB devices, `qvm-block attach sys-usb:2-x` gives the same error

**Comment by farrilis** [comment]
to clarify:

`qvm-usb list` 

lists the USB hub as DEVID 2-3, and all other devices as DEVID 2-x

Maybe this is a bug, but I believe it was always this way.

**Comment by marmarek** [comment]
> 4.0.17-1.fc25 now installed.

You need to restart the widget, for changes to take effect. You can do that by killing qui-devices process (it will be restarted automatically).



> to clarify:
> 
> `qvm-usb list`
> 
> lists the USB hub as DEVID 2-3, and all other devices as DEVID 2-x

Can you provide full line? Hub itself should not be listed...

> `qvm-block attach sys-usb:2-x` gives the same error

Once again: devices listed with qvm-usb can be attached with qvm-usb. qvm-block can attach devices listed with qvm-block.

**Comment by farrilis** [comment]
> Can you provide full line? Hub itself should not be listed...

This is probably wrong, I'm made another assumption more likely. The device has a string of numbers and letters (`000a_000a`) in the description field of `qvm-usb list` output, and is still listed when no devices are plugged in. This led me to my assumption! :D

I did `killall qui-devices`, Device widget now works! Thanks for the help!

If you would like any other information I am happy to provide it, I'm aware that my hardware (Librem 13) is perhaps not the most common available

**Comment by e6lk7dqzm83p** [comment]
Hi,
I think I *may* have a related issue.  When I restart my machine I am unable to attach devices to a DVM via the device widget, but when I manually killed the device widget (via `killall qui-devices`) it restarted and worked.

I'm not sure why this doesn't work on boot.

I have qubes-desktop-linux-manger 4.0.18-1.fc25.

**Comment by andrewdavidwong** [comment]
> Hi,
> I think I _may_ have a related issue. When I restart my machine I am unable to attach devices to a DVM via the device widget, but when I manually killed the device widget (via `killall qui-devices`) it restarted and worked.
> 
> I'm not sure why this doesn't work on boot.
> 
> I have qubes-desktop-linux-manger 4.0.18-1.fc25.

Can you provide more details about why you were unable to attach devices using the device widget and how it worked after you restarted it?

**Comment by e6lk7dqzm83p** [comment]
@andrewdavidwong sorry, but I have no idea why this worked.  I noticed I was having an issue that seemed to crop up out of nowhere (possibly after an update) and googling brought me to this issue.  I then followed the suggestions and it worked.

I'm happy to do any tests/diagnostics you'd like.

**Comment by e6lk7dqzm83p** [comment]
Update: It appears after some period of time I have to kill qui-devices again, have it restart, and then I'm able to attached devices.

**Comment by andrewdavidwong** [comment]
> Update: It appears after some period of time I have to kill qui-devices again, have it restart, and then I'm able to attached devices.

Thanks for the update. Perhaps this will give the devs enough of a hint to work off of. If not, I'm sure they'll ask for appropriate logs or tests. :slightly_smiling_face:

**Comment by marmarek** [comment]
It happens to me few times, but sadly I wasn't able to collect enough info to diagnose it further. There is an update in current-testing (https://github.com/QubesOS/updates-status/issues/1118) including (among other things) more verbose logging. If you could install it and report any errors you've got (should be as notifications), that would be helpful.

**Comment by e6lk7dqzm83p** [comment]
Hi,
It appears the issue does persist in spite of the update (I thought the issue may have been resolved hence my delayed response).  I did get an "Error" notification when I tried to attach my device this time, but no other information.

**Comment by brendanhoar** [comment]
> Hi,
> It appears the issue does persist in spite of the update (I thought the issue may have been resolved hence my delayed response). I did get an "Error" notification when I tried to attach my device this time, but no other information.

Same here. Interestingly, I find that restarting the target VM always allows it to work after an Error.

However, if you want it to work disposable VMs, you can't really restart those (it's a different VM on every start) and therefore I always get the error messages and cannot use the menu for them.

Brendan

Brendan

**Comment by marmarek** [comment]
This should be fixed in https://github.com/QubesOS/updates-status/issues/1178

**Comment by e6lk7dqzm83p** [comment]
Hi,

I still have the issue of qui-devices becoming unresponsive and needing to be killed/restarted.

**Comment by andrewdavidwong** [comment]
> Hi,
> 
> I still have the issue of qui-devices becoming unresponsive and needing to be killed/restarted.

Can you please confirm your version of `desktop-linux-manager`?

Possibly related: #3440

**Comment by e6lk7dqzm83p** [comment]
Hi,
I have qubes-desktop-linux-manger 4.0.19-1.fc25-noarch.

**Comment by marmarek** [comment]
>  I have qubes-desktop-linux-manger 4.0.19-1.fc25-noarch.

Fixed version is 4.0.20, still in testing repository (see [here](https://www.qubes-os.org/doc/software-update-dom0/#testing-repositories)). Lets keep this one closed until you confirm it still happens in the new version too.
