### ISSUE TITLE
Xen causes kernel panic during install - USB boot

### ISSUE THREAD

**Issue by orjanj** [QubesOS/qubes-issues#5374]
**Qubes OS version**
Qubes Release 4.0.2-rc1

**Affected component(s) or functionality**
XEN.

**Brief summary**
Trying to install Qubes on a Asus Zenbook UX433FN (yes, it's not under the hardware list, the 4.0.1 release didn't work, but the 4.0.2 got me further in to the installation; seems like it's working almost!) and I get a kernel panic.
The fully message can be seen below and in a attached screenshot.

**To Reproduce**
1. To stop the boot loop I've added 'noapic acpi=off' to the options in BOOTX64.cfg.
Also tried to add 'dis_ucode_ldr' (no effect).
2. Inserted the USB drive to the laptop and tried to boot it.
3. Got kernel panic (message shown below).

**Expected behavior**
Expecting to see a installation menu.

**Actual behavior**
Kernel Panic.

**Screenshots**
Could be found [here](https://imgur.com/a/uSCfCsN).

**Additional context**
The screenshots shows the message below in more details;

> (XEN) Xen BUG at x86_64/mm.c:691
(XEN) ----[ Xen-4.8.5-7.fc25  x86_64  debug=n    Not tained ]----
(XEN) CPU:    0
(XEN) RIP:    e008:[<ffff82d080622718>] zap_low_mappings+0x68/0x70
(XEN) RFLAGS: 0000000000010097   CONTEXT: hypervisor
...
...
(XEN) Xen code around <ffff82d080622718> (zap_low_mappings+0x68/0x70):
(XEN)  ff 0f 1f 80 00 00 00 00 <0f> 0b 66 0f 1f 44 00 00 41 57 41 56 49 be 00 00
(XEN) Xen stack trace from rsp=ffff82d080827da0:
...
...
(XEN) Xen call trace:
(XEN)     [<ffff82d080622718>] zap_low_mappings+0x68/0x70
(XEN)     [<ffff82d080627b61>] __start_xen+0x2041/0x3630
(XEN)
(XEN)
(XEN) ******************************************
(XEN) Panic on CPU 0:
(XEN) Xen BUG at x86_64/mm.c:691
(XEN) ******************************************
(XEN)
(XEN) Reboot in five seconds...

**Solutions you've tried**
[Adding dis_ucode_ldr to the BOOTX64.cfg file](https://askubuntu.com/questions/1146431/no-possible-way-to-install-ubuntu-on-asus-zenbook-ux433fn) (this did work to initialise a Ubuntu LiveCD, without this param you were unable to boot Ubuntu).
Have also added 'noapic acpi=off' to the options line in BOOTX64.cfg, without getting further.
Also tried to add 'nouveau.modeset=0', no changes to this.

_Hardware (Asus Zenbook UX433FN):_
* Intel i7 8565U
* NVIDIA GeForce MX150

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
[UEFI troubleshooting](https://www.qubes-os.org/doc/uefi-troubleshooting/).

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
None.

**Comment by brolund** [comment]
I have the same issue and error message after using the 
> noapic acpi=off
to get past panic 
> IO-APIC + timer doesn't work!

Hardware: Dell XPS 13 7390 2-in-1

**Comment by orjanj** [comment]
Have tried the same steps with the *-rc2 and still doesn't work.
Are looking into if there's any other params to use to go around this issue.
Any new status in this issue @andrewdavidwong?

**Comment by andrewdavidwong** [comment]
> Any new status in this issue @andrewdavidwong?

Nope.

**Comment by hs-j** [comment]
Here is my error message (Dell XPS 13 7390 2-in-1 [i7-1065G7]). This is simply booting off a flash drive with Qubes-R4.0.3-x86_64.iso  dd'ed onto it without editing anything.

sudo dd if=Qubes-R4.0.3-x86_64.iso of=/dev/sdb && sync

My initial naive thought was that fastboot was messing with it somehow. I tried disabling it both in BIOS and Windows to no avail.

![11](https://user-images.githubusercontent.com/25859047/74084509-93f70280-4abb-11ea-9ed1-ed869e0c6268.png)
![22](https://user-images.githubusercontent.com/25859047/74084514-9eb19780-4abb-11ea-82db-381dd7e50cb0.png)
![33](https://user-images.githubusercontent.com/25859047/74084533-c3a60a80-4abb-11ea-989d-c8f71853b8c9.png)

**Comment by marmarek** [comment]
The key message is "MP-BIOS bug: 8254 timer not connected to IO-APIC".
First, try updating BIOS, as this looks like a BIOS bug. If that doesn't help, add `apic_verbosity=debug` option to get more details.
But I'm afraid the only option to get it working is to Dell fix the BIOS bug, software workarounds are unlikely to help here.

**Comment by hs-j** [comment]
@marmarek, I'm quite inexperienced in debugging such problems. I updated my BIOS to the latest version (1.1.3, 10/11/2019) which didn't change anything. I then mounted the EFI partition of my flash drive, appended "apic_verbosity=debug" to the /EFI/BOOT/BOOTX64.cfg file, and unmounted. This didn't change my output at all, which makes me think this is the wrong file to modify. Where should I be adding the "apic_verbosity=debug" option?

**Comment by alexander-jr** [comment]
would like to confirm that I'm getting the same bug on a ASUS UX433FN, updating the BIOS to the latest version 309 hasn't helped, out of interest have tried the qubes 4.1 to no avail as well

**Comment by marmarek** [comment]
There is a discussion about this on xen-devel ML: https://markmail.org/thread/qsnxiknqalo4qoke
Generally it looks as a Xen bug, but there is no consensus yet how to fix it.

**Comment by 3-O** [comment]
The same bug ("MP-BIOS bug: 8254 timer not connected to IO-APIC") occurs to me with Qubes 4.0.3 on an Asus Zenbook UX433F. Looks like the thread linked by @marmarek reports some progress on this issue.

**Comment by tobbe0xFF** [comment]
Getting a very similar error as everyone else reporting in this thread when trying to install Qubes 4.0.3 from USB on a system with MSI B360M Mortar.
The difference in error message starts after:
`ENABELING IO_APIC IRQs
-> Using old ACK method`
instead of `..MP-BIOS bug`
I get 
`------- [  Xen-4.8.5-14.fc25 x86_64 debug=n Not tained 1 ] --------`
and the rest very similar to screenshot 2/3 from @hs-j 

Looking at the thread posted by @marmarek it seems that someone got it working by updating Xen code in a message from March 18. What would it take to include that update with Qubes? Any chance that could make it into Qubes 4.1 or even an earlier service release?

**Comment by taxmeifyoucan** [comment]
I experience the same issue, XPS 13 7390, Intel i7-10510U. When I try to boot from installation volume, it get stuck at rebooting with similar logs as @hs-j. Is there any closure on this issue, any solutions I can try? Can't wait to run Qubes!

**Comment by hridikamene** [comment]
Hi all, any updates on this issue?

**Comment by tSC-1** [comment]
Hi Marek!

Yes, I would also like to know if there are any news for this topic.
I have tried to install (and I would like to go on with very much...!) to install Qubes 4.03.) on three more Laptops of ASUS:
ExpertBook 9. ZenBook 14 and Zephyrus Duo 15.
The all have Intel CPUs of the 10th generation (one i5, one i7 and one i9)...
On each of them I have installed the newest BIOS what ASUS is delevering so far...

And with all of them I am getting the same problem like described here before.

When I try to install Qubes 4.03. all of them are showing the error:
"Panic om CPU 0: 
IO-APIC + timer doesn't work..."
 The messages are the same which hs-j has described/showed in his pictures February 8 2020.

So I would like to know if there is a solution to come... for these kind of errors.

And do you know if this error is typical for Laptops using the Intel CPUs of the 10th generation?

And one more question:
Because your Hardware Compatibility List (HCL) more or less is showing older Hardware...
When you would buy a new Laptop especially for using Qubes OS what you would buy for yourself?

I have seen the NitroPad... But excuse me... Price seems to be fair...The main problem for me with that "certified for Qubes OS" Hardware is the screen resolution (1366x768 )... because I am used to have many open windows... and with cubes OS I would like to have many open Qubes... and would like to see as much infomartions at the same time as possible... So I would like to have a Notebook with UHD or FullHD at least and minimum 32 GByte RAM better 64 Gbyte RAM...

Can you still recommend Purism Laptops?
Or something else...?

Do I sound a bit desperated...?
Laugh... Yes I am.

Because your HCL doesn't help really...
And your Recommended System Requirements are so unspecific that...
The certified Hardware so far is showing this NitroPad X230 (and Insorgo Privcy Beast X230...) only...
And the help under " Advice to find a VT-d capable notebook" ( https://groups.google.com/d/msg/qubes-users/Sz0Nuhi4N0o/ZtpJdoc0OY8J ) ... doesn't help either... the last entry there is from July 2016.

So, I would be happy if you could give some more specific advice
OR at least some information if you think that the next version of Qubes OS 4.1. could solve the described issue 
here with these Laptops I already have...?

Thank you in advance!

**Comment by andrewdavidwong** [comment]
@tSC-1: Sorry, but most of your comment is off-topic for this issue. Please carefully read our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/). We ask that you please post your off-topic comments and questions on the [`qubes-users` mailing list or forum](https://www.qubes-os.org/support/) instead. Thank you for your understanding.

**Comment by tobbe0xFF** [comment]
Now also experiencing this issue on a Gigabyte Aorus Pro with i7-9700K.
I understand this issue may take time to debug and that it may not be top priority, but it would be assuring to hear from someone in the dev team what you have learned about this issue so far and if you have some idea of how it can be addressed? E.g. would it feasible to clone the Xen repo, patch the code with what is found in the link from @marmarek, build a custom ISO and install that way?

**Comment by tSC-1** [comment]
... have tried to install (and I would like to go on with this
very much...!) Qubes 4.03.) on three of our Laptops from ASUS:
ExpertBook 9. ZenBook 14 and Zephyrus Duo 15.
They have all Intel CPUs of the 10th generation (one i5, one i7 and one
i9)...
On each of them I have installed the newest BIOS what ASUS is
delevering so far...

When I try to install Qubes 4.03. all of them are showing the error:
"Panic om CPU 0: 
IO-APIC + timer doesn't work..."
 
Withe the same result what hs-j (https://github.com/hs-) has shown under
his comment here February 8th.

Do you know if this error is typical for Laptops using the Intel CPUs
of the 10th generation?

Any solution?

**Comment by djt3** [comment]
I have the exact same problem on an ASUS Z490-G with the i5 10600k.

**Comment by ronfduncan** [comment]
I can confirm that [the patch](https://markmail.org/thread/qsnxiknqalo4qoke) works correctly - and that the Zenbook 15 (UX533F) boots correctly after performing the following steps.  The APIC timer issue has been resolved.

Note that distributing a ISO is not a good idea, so steps are better.

1. Follow the guide at https://www.qubes-os.org/doc/qubes-iso-building/ to download the Qubes source on Fedora
2. Note: This patch works with Qubes 4.1 (RC) with the current repository
3. Create a file called patch-qubes-zenbook.patch in ~/qubes-builder/qubes-src/vmm-xen with the patch content at the bottom of this message.
4. Add this patch to the xen.spec.in file in vmm-xen
5. Create the ISO as per the documentation

`diff --git a/xen/arch/x86/hpet.c b/xen/arch/x86/hpet.c
index 86929b9ba1..93a34792b2 100644
--- a/xen/arch/x86/hpet.c
+++ b/xen/arch/x86/hpet.c
@@ -765,6 +765,15 @@ int hpet_legacy_irq_tick(void)


 static u32 *hpet_boot_cfg;


+void hpet_disable_legacy(void)
+{
+    u32 cfg = hpet_read32(HPET_CFG);
+    printk(XENLOG_INFO "%s HPET_CFG %08x\n", __func__, cfg);
+    cfg &= ~HPET_CFG_LEGACY;
+    printk(XENLOG_INFO "%s HPET_CFG %08x\n", __func__, cfg);
+    hpet_write32(cfg, HPET_CFG);
+}
+
 u64 __init hpet_setup(void)
 {
     static u64 __initdata hpet_rate;
@@ -804,6 +813,8 @@ u64 __init hpet_setup(void)
     return hpet_rate + (last * 2 > hpet_period);
 }


+#include <asm/delay.h>
+
 void hpet_resume(u32 *boot_cfg)
 {
     static u32 system_reset_latch;
@@ -842,11 +853,33 @@ void hpet_resume(u32 *boot_cfg)
                    cfg & HPET_TN_RESERVED, i);
             cfg &= ~HPET_TN_RESERVED;
         }
+        if (i == 0) {
+            cfg |= HPET_TN_ENABLE | HPET_TN_PERIODIC | HPET_TN_SETVAL |
+                   HPET_TN_32BIT;
+        }
         hpet_write32(cfg, HPET_Tn_CFG(i));
+        if (i == 0) {
+#define NSEC_PER_SEC    1000000000L
+            uint64_t delta;
+            unsigned int now;
+            unsigned int cmp;
+            u64 hpet_rate = hpet_setup();
+            uint32_t mult = div_sc((unsigned long)hpet_rate,
+                                     1000000000ul, 32);
+            uint32_t shift = 32;
+            printk(XENLOG_INFO "hpet mult %d shift %d\n", mult, shift);
+            delta = ((uint64_t)(NSEC_PER_SEC / HZ)) * mult;
+            delta >>= shift;
+            now = hpet_read32(HPET_COUNTER);
+            cmp = now + (unsigned int)delta;
+            hpet_write32(cmp, HPET_Tn_CMP(i));
+            udelay(1);
+            hpet_write32(delta, HPET_Tn_CMP(i));
+        }
     }


     cfg = hpet_read32(HPET_CFG);
-    cfg |= HPET_CFG_ENABLE;
+    cfg |= HPET_CFG_ENABLE | HPET_CFG_LEGACY;
     hpet_write32(cfg, HPET_CFG);
 }


diff --git a/xen/arch/x86/io_apic.c b/xen/arch/x86/io_apic.c
index e98e08e9c8..b62dea190a 100644
--- a/xen/arch/x86/io_apic.c
+++ b/xen/arch/x86/io_apic.c
@@ -34,6 +34,7 @@
 #include <asm/desc.h>
 #include <asm/msi.h>
 #include <asm/setup.h>
+#include <asm/hpet.h>
 #include <mach_apic.h>
 #include <io_ports.h>
 #include <irq_vectors.h>
@@ -2047,6 +2048,7 @@ void __init setup_IO_APIC(void)
     setup_IO_APIC_irqs();
     init_IO_APIC_traps();
     check_timer();
+    hpet_disable_legacy();
     print_IO_APIC();
     ioapic_pm_state_alloc();


diff --git a/xen/include/asm-x86/hpet.h b/xen/include/asm-x86/hpet.h
index fb6bf05065..531e94e904 100644
--- a/xen/include/asm-x86/hpet.h
+++ b/xen/include/asm-x86/hpet.h
@@ -82,6 +82,7 @@ void hpet_broadcast_enter(void);
 void hpet_broadcast_exit(void);
 int hpet_broadcast_is_available(void);
 void hpet_disable_legacy_broadcast(void);
+void hpet_disable_legacy(void);


 extern void (*pv_rtc_handler)(uint8_t reg, uint8_t value);`

**Comment by cobordism** [comment]
I can report the same error on a System76 Lemur Pro (lemp10).
Will probably give up and wait for 4.1

**Comment by ideologysec** [comment]
4.1 alpha does not resolve the issue; this is a bug in Xen's handling of the ACPI/IRQ/HPET timers and interrupts; it needs to be fixed upstream and I don't think there's a plan for that.

**Comment by marmarek** [comment]
> it needs to be fixed upstream and I don't think there's a plan for that.

There kind of is:
RFC fix: https://xen.markmail.org/thread/qieamnwlm5l4gqkl
classified as 4.15 release blocker: http://markmail.org/message/fnf4z2ruexwdfmkb

**Comment by ideologysec** [comment]
@marmarek good to know. What are Qubes' plans regarding Xen 4.15 and, say, 4.1?

**Comment by h01ger** [comment]
any chance this will land in Qubes 4.0.x?

**Comment by ideologysec** [comment]
It was backported, but it didn't appear to land in the 4.0.4 ISO

**Comment by marmarek** [comment]
No, it wasn't backported to R4.0. And before considering it, it first needs to work better - currently it fixes an issue on some hardware, but breaks support for others (https://github.com/QubesOS/qubes-issues/issues/6423) - which is actually very strong reason to _not_ backport it to a stable release.

**Comment by h01ger** [comment]
hm. and any ETA for a new alpha 4.1 iso, if only on openqa.qubes-os.org? :)

**Comment by TheNameIsSamSamuelson** [comment]
> hm. and any ETA for a new alpha 4.1 iso, if only on openqa.qubes-os.org? :)

Also waiting for it here. Unsuccessfully tried to build the patched version as explained above. Because to do it, a working version of cubes OS is needed(as build instructions explain)...

**Comment by ioleo** [comment]
Having the same issue here. Tried to build the 4.1, however it failed 20hrs into the process in failed when building template fc30.

1. Is there a way to retry/resume `make qubes` from the last failed step? It seems my build failed due to some network issues.
2. How long is the whole process supposed to take? It's my first time trying to build qubes. Knowing what to expect timewise would help me to plan a window for another attempt.
3. Or could qubes team provide an updated 4.1 ISO with this patch?
4. Maybe there is some shorter way, not building the whole Qubes from scratch? Perhaps it's possible to download prebuilt 4.1 or 4.0.4 and just update Xen? If so I would greatly appreciate hints how to do that.

I'd like to try the Xen patch and see if it helps for my hardware (Asus Zenbook with i9-10980HK). BIOS is updated, and secure boot disabled.

**Comment by ioleo** [comment]
I can confirm I managed to build Qubes 4.1 ISO on fedora-32 AppVM and succesfully installed on Asus Zenbook Pro Duo UX 581, so the Xen patch worked for me.

**Comment by svdmsvdm** [comment]
@ioleo do you still have your iso?

**Comment by hbswn** [comment]
I had the same using the latest 4.0.4 ISO, but I already had an installed Qubes OS 4.0.4rc2, so I fixed that.

Applied this patch to the stable 4.8 branch: [x86/timer: Fix boot on Intel systems using ITSSPRC static PIT clock gating](https://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=f6f787de989655747795e216a7ca5d16e8cd7609)

```
git://xenbits.xenproject.org/xen.git
cd xen
git checkout stable-4.8
patch -p1 </tmp/Xen-Skylake-8259.patch
./configure
make
ls -l ./dist/install/usr/lib64/efi/xen-4.8.5.efi
```

Not sure whether more patches should be applied, but this one seems made for this problem.

Hans

**Comment by hbswn** [comment]
. . . but I still get:
```
[    82.322] (EE) AIGLX error: Calling driver entry point failed
[    82.323] (EE) AIGLX: reverting to software rendering
```

**Comment by d3m3n7** [comment]
Hello @ioleo, 
I'm having this issue on a DELL XPS 13 9380.
Could you explain what steps did you take in order to build Qubes and install the Xen patch?
I'm afraid this will be too complicated or time consuming for me so it'd be great to have a rough idea of what to expect.
Thanks in advance

**Comment by hbswn** [comment]
It was already fixed in  [io-apic issues on install boot for 4.1 NUC10i5FNH #6372](https://github.com/QubesOS/qubes-issues/issues/6372)

That's "testing R4.1"

Hans

**Comment by hbswn** [comment]
@d3m3n7 , 
> Hello @ioleo,
> I'm having this issue on a DELL XPS 13 9380.

If you do not mind running the development 4.1 Qubes, try the latest test ISO from [Index of /qubes/iso/](https://qubes.notset.fr/iso/), currently :

>     Qubes-20210424-x86_64.iso 1
>     24-Apr-2021 04:53
>     5408555008

Hans

**Comment by ideologysec** [comment]
Testing with the Qubes-20210424-x86_64.iso from above, still having the same issue on a Dell XPS 9570 (2018 model year, i7-8750H, Coffee Lake). apic_verbosity=debug does not appear to provide additional information.

![IMG_2350](https://user-images.githubusercontent.com/790061/116170415-aad34600-a6bb-11eb-83cf-4957b707f9d5.jpeg)
![IMG_2351](https://user-images.githubusercontent.com/790061/116170426-b161bd80-a6bb-11eb-99b9-e872e26690a8.jpeg)

The computer was set up to run macOS via OpenCore, and I know that that can mess with/change APIC and the HPET timers (which may or may not be related). What additional info can I provide or troubleshooting can I do?

**Comment by hbswn** [comment]
This is, what M meant in his comment: ["currently it fixes an issue on some hardware, but breaks support for others"](https://github.com/QubesOS/qubes-issues/issues/5374#issuecomment-801558858)

Hans

**Comment by ideologysec** [comment]
Interesting. I see the same issue on both the Qubes 4.0.4 and Qubes 4.1-2021-April iso - no change, in other words.

**Comment by hbswn** [comment]
Ah, maybe my patch works for you as well ?

But I could boot the new ISOs and it failed on the 4.0.4 version.

I have found one in-between Xen patch ["x86: avoid HPET use on certain Intel platforms"](https://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=25909056dea63f114a8de6f2e5152f6ea143e7d6), that disables the HPET timer for Coffee Lake systems, but I'd expect it to be in the 4.14+ based Qubes so then it's not likely to fix it.

It is a patch for [Xen 4.12.2](https://xenproject.org/downloads/xen-project-archives/xen-project-4-12-series/xen-project-4-12-2/) and something similar was applied to [Linus kernel](https://github.com/torvalds/linux/blob/master/arch/x86/kernel/early-quirks.c) .

It compiles on my locally checked out xen 4.8.5. (same version as in Qubes 4.0 )

No guarantees ;-)

Hans

**Comment by hbswn** [comment]
@ideologysec

[LinuxReviews](https://linuxreviews.org/) has a good description of the [High Precision Event Timer (HPET) on Intel Coffee Lake systems](https://linuxreviews.org/Linux_Kernel_Disables_Coffee_Lakes_HPET_On_The_Grounds_That_It_Is_%22Unreliable%22). And [Kernel Bug report 203183](https://bugzilla.kernel.org/show_bug.cgi?id=203183) describes how to reproduce the issue.

On Xen 4.14 (so on Qubes 4.1) you can disable HPET using a [command-line option hpet=0](https://xenbits.xen.org/docs/4.14-testing/misc/xen-command-line.html#hpet).

Maybe that helps?

Hans

**Comment by ideologysec** [comment]
1. I was placing `apic_verbosity=debug` in the wrong place; it's a Xen option, not a vmlinuz one. 
2. it reveals that HPET is ignored since it's considered unreliable anyway
3. booting with `noapic` does result in a change, but just to a more general PANIC that results in the computer rebooting almost immediately.
4. I've removed both the SSD (which included the bootloader), and the wireless card in an attempt to get down to a more minimal system, but that seems to make no difference either.

There was a report of this computer booting and installing Qubes 4.1 successfully in the HCL (Dell XPS 9570), though with a slightly older BIOS version. I really thing something got twiddled in the firmware to cause this issue; my next steps will be through the dangerous path of downgrading the BIOS and seeing if either the reflashing or the version make a difference.

**Comment by nunesgh** [comment]
I experience the same issue on Dell Vostro 15 5590 (Intel Core i7 -10510U) when trying to install Qubes Release 4.0.4.

**Comment by aaronjanse** [comment]
See the relevant xen-devel mailing list discussion. If someone could test the patch, that would be fantastic. I want Qubes to work on my laptop but I don't have motivation to compile Xen myself right now https://markmail.org/thread/qsnxiknqalo4qoke#query:+page:1+mid:byon4l7mtnwf6whz+state:results

Fwiw, I've gotten the Qubes 4.1 ISO working on my Dell XPS 13 (7390) by disabling suspend in my BIOS, but I really hope Qubes could one day work without doing so

**Comment by hashkeeper** [comment]
ahh very cool. thanks for the info @andrewdavidwong
