### ISSUE TITLE
Fix broken links in the docs' FAQ

### ISSUE THREAD

**Issue by strugee** [QubesOS/qubes-issues#5537]
**Qubes OS version (if applicable)**

N/A

**Affected component(s) or functionality (if applicable)**

doc

**Brief summary**

https://www.qubes-os.org/faq/ is full of weird broken Markdown links. E.g. `[Xen]` instead of just "Xen" but with a link.

**Additional context**

This content landed in QubesOS/qubes-doc#898; @luzeal did you use a script to do the conversion? If so it'd probably be easier to just fix the script to handle links right. If not I'd be happy to send a PR cleaning this up manually - just thought I'd ask before I do a bunch of work.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None

**Comment by unman** [comment]
@strugee @andrewdavidwong  Whatever the issue here was, it seems to have been fixed .
Please close.

**Comment by strugee** [comment]
It's not fixed. I went through and fixed some of them but not all and submitted what I had. Just do a Ctrl-F for `[` and you'll find more.

**Comment by andrewdavidwong** [comment]
@luzeal, would you be willing to finish this?

**Comment by unman** [comment]
@andrewdavidwong I think it is now fixed, and can be closed.(Except cryptsetup note, "shows useful status" - I had no idea what that was supposed to link to and it makes sense as parenthetical remark.)

**Comment by andrewdavidwong** [comment]
Closing this as resolved. If you believe the issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen this. Thank you.
