### ISSUE TITLE
Black Screen when installing 4.0.3 on AMD Ryzen 4750U

### ISSUE THREAD

**Issue by dylangerdaly** [QubesOS/qubes-issues#5980]
**Qubes OS version**
4.0.3 and 4.1 test ISO

**Affected component(s) or functionality**
Installer / dom0 output

**Brief summary**
When trying to install Qubes 4.0.3 into a Ryzen 4750U based laptop, I see xen output, it relinquishes vga to dom0, then black.

**To Reproduce**
_Steps to reproduce the behavior:_
_1. Obtain a Laptop with a Ryzen 4750U APU
_2. Attempt to boot a USB 4.0.3 or 4.1 ISO
_3. Be sad

**Expected behavior**
Anaconda/Installer should be visible

**Actual behavior**
Black screen

**Screenshots**
N/A

**Additional context**
N/A

**Solutions you've tried**
I've tried following [UEFI Troubleshooting](https://www.qubes-os.org/doc/uefi-troubleshooting/) with all sorts of combinations unsuccessfully.

I've also attempted to just move my NVMe drive and boot a kernel-latest (5.6.16 and even 5.7.10 from current-testing) however I still end up with a black screen.

It's almost as if the amdgpu isn't being attached to dom0, or it could also be some sort of iommu issue.
Does anyone know how I can output dom0 kernel output to Xen's serial? Might help with logs?

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
_A list of links to the Qubes documentation (or other relevant software documentation) pages you have already consulted._

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
_A list of links to other bug reports, feature requests, or tasks in the qubes-issues tracker (or "none" if you didn't find any). Do not describe any other unreported bugs, features, or tasks here._

**Comment by dylangerdaly** [comment]
I managed to enabled logging, where it prints dom0's dmesg super slow, line by line.

```
efifb: cannot reserve video memory at 0x60000000
efi: EFI_MEMMAP is not enabled
```

Then it crashes but it continues to come all the way to Anaconda confirming it's a GPU/Memory Issue

**Comment by tasket** [comment]
I have the same problem with my Thinkpad T14 Ryzen 4750U.

Here's a link to the [qubes-users thread.](https://groups.google.com/d/msgid/qubes-users/229dd210-ad9f-43b4-984b-6ad8905091f4o%40googlegroups.com)

**Comment by dylangerdaly** [comment]
Quick update to this, I've successfully compiled an ISO using @marmarek's Github repo, specifically compiling Xen 4.14, this has successfully booted on my X13.

I can see dat Anaconda, I'm going to start looking at diffing 4.13.1 and 4.14 to see if it's possible to cherrypick the fix into 4.8 (Qubes 4.0.3)

**Comment by zaoqi** [comment]
I have the same problem with Asus Vivobook 14 Ryzen 4700U

**Comment by mukens** [comment]
> I managed to enabled logging, where it prints dom0's dmesg super slow, line by line.
> 
Same here on a Lenovo ThinkPad L14 gen1 with AMD Ryzen 5. I have to add vga=keep as a xen parameter when booting though, otherwise i get only a black screen.

**Comment by dylangerdaly** [comment]
This has been fixed.

**Comment by EvTheFuture** [comment]
> This has been fixed.
> (Install R4.1)

The builds available of 4.1 does not fix the problem on the ThinkPad L14 gen1 with an AMD Ryzen 4500U. Black screen and with xen parameter vga=keep it is super slow and eventually get a kernel panic while booting the installer.

I've tried to build 4.1 from source, but haven't been able to get it to build yet. Will spend some more time on trying to get it to build hopefully later today.

**Comment by EvTheFuture** [comment]
I tried to build 4.1 on a regular fc (no VM) since I don't use QubesOS yet. But it seem to be dependencies to the fc32 template.

I tried installing QubesOS on every machine i currently have available just to try to build an iso with xen 4.14 and a newer kernel than 5.4, but none of my machines had the necessary specs to actually boot after the installation.

I got a friend of mine to build an iso of QubesOS from master (as described in [this thread](https://qubes-os.discourse.group/t/qubes-support-on-amd-4000-series-lenovo-x13-t14/202/36)) which created an iso with kernel 5.9. Unfortunately it seems like there might be some problem with the kernel or the building of the kernel. When I try to boot the ISO XEN start, but fails to start the kernel. (This may be due to a bad build).

![IMG_20201220_233802_2](https://user-images.githubusercontent.com/66333723/102880384-82a4b380-444b-11eb-9ac1-00fff7b6b029.jpg)

Does anyone have a 4.1 iso with a new kernel (5.9 or 5.10) just to see if it will boot properly and this issue has been fixed?

**Comment by 0spinboson** [comment]
> I tried to build 4.1 on a regular fc (no VM) since I don't use QubesOS yet. But it seem to be dependencies to the fc32 template.
> 
> I tried installing QubesOS on every machine i currently have available just to try to build an iso with xen 4.14 and a newer kernel than 5.4, but none of my machines had the necessary specs to actually boot after the installation.
> 
> I got a friend of mine to build an iso of QubesOS from master (as described in [this thread](https://qubes-os.discourse.group/t/qubes-support-on-amd-4000-series-lenovo-x13-t14/202/36)) which created an iso with kernel 5.9. Unfortunately it seems like there might be some problem with the kernel or the building of the kernel. When I try to boot the ISO XEN start, but fails to start the kernel. (This may be due to a bad build).
> 
> ![IMG_20201220_233802_2](https://user-images.githubusercontent.com/66333723/102880384-82a4b380-444b-11eb-9ac1-00fff7b6b029.jpg)
> 
> Does anyone have a 4.1 iso with a new kernel (5.9 or 5.10) just to see if it will boot properly and this issue has been fixed?

I dunno if fixed, but iso is here: https://openqa.qubes-os.org/tests/14505/asset/iso/Qubes-4.1-20201218-x86_64.iso

**Comment by EvTheFuture** [comment]
> I dunno if fixed, but iso is here: https://openqa.qubes-os.org/tests/14505/asset/iso/Qubes-4.1-20201218-x86_64.iso

Unfortunately these builds use version 5.4 still and 5.4 does not work on this laptop.

**Comment by dylangerdaly** [comment]
qubes-builder shouldn't have any dependency on running on Qubes, I use Fedora Silverblue to build Qubes personally and its worked quite well.

I haven't used an L14 before, but it's also possible UEFI/ACPI tables are putting Xen in a bad state

**Comment by EvTheFuture** [comment]
I reinstalled fc32 on my old desktop and finally got it to build.

The only thing I changed in builder.conf was to use the net el from master and remove awesome (which failed to build).

Unfortunately the kernel won't boot as seen here:
![IMG_20210111_030134_1](https://user-images.githubusercontent.com/66333723/104333114-29332000-54f1-11eb-85a1-af7ed9e57c2f.jpg)

I don't know why this is happening. I can successfully boot xen with 5.10 kernel from Alpine 3.13rc2.

Any ideas?

**Comment by n0madK** [comment]
Then you change the kernel to master branch, it builds kernel-latest instead of kernel. Then for some reason, the builder pulls `kernel` from upstream fedora when building the iso (5.10.2 currently). That kernel is compressed with zstd which xen does not support, hence the `ELF: not an ELF binary` message.

You can check if this it the case by mounting the iso and checking in the isolinux directory.

To get the ISO to build with the kernel-latest, I tried the guidance at https://www.mail-archive.com/qubes-devel@googlegroups.com/msg04676.html, but this also did not seem to use my local kernel-latest.

I ended up removing the line `-%define name_suffix -latest` from `qubes-src/linux-kernel/kernel.spec.in` then
`make linux-kernel
make iso`
To get my kernel to build as `kernel` which the builder then loaded into the iso.

**Comment by tweidinger** [comment]
Tried the workaround from @n0madK and the guidance from mail-archive and still got `ELF: not an ELF binary`.

> You can check if this it the case by mounting the iso and checking in the isolinux directory.

The file was still in zstd format even when following this approach

> I ended up removing the line %define name_suffix -latest from qubes-src/linux-kernel/kernel.spec.in then

I just removed the line, re-made the kernel and iso. I had probably an image cached from a previous build and will test with a fresh vm if this could be the cause.

For the general issue of missing zstd compression I found that https://bugzilla.redhat.com/show_bug.cgi?id=1898662 mentions the issue as merged into stable fedora 32. And the fedora tracker marked the issue as obsoleted by xen  xen-4.13.2-4.fc32 https://bodhi.fedoraproject.org/updates/FEDORA-2020-4ff32ef9be maybe there is an regression in xen-4.14 or a missing port?

Current kernel tested on my machine was 5.10.18-100 but seemingly the issue persists (for now).

**Comment by n0madK** [comment]
This is the builder.conf I used to build the 4.1 iso (mostly from upstream). This is pulled mostly from the builder examples.
```
# vim: ft=make

VERBOSE ?= 2

BACKEND_VMM ?= xen

GIT_BASEURL ?= https://github.com
GIT_PREFIX ?= QubesOS/qubes-

RELEASE ?= 4.1

DIST_DOM0 ?= fc32
DISTS_VM ?= 

BRANCH_linux_kernel = stable-5.10

COMPONENTS = \
    installer-qubes-os \
    linux-yum \
    vmm-xen \
    linux-kernel \
    builder-rpm \
    lorax-templates \
    meta-packages

BUILDER_PLUGINS ?= builder-rpm

USE_QUBES_REPO_VERSION = $(RELEASE)

INSTALLER_KICKSTART=/home/user/qubes-src/installer-qubes-os/conf/iso-full-online.ks
```
Then I reset branched the linux-kernel repo `stable-5.10` to match `BRANCH_linux_kernel = stable-5.10` and removed the `name_suffix` from the kernel.spec.in.

I think that was all I needed to do to get the iso to pickup my local kernel instead of the upstream fedora one.

**Comment by tweidinger** [comment]
Hi @n0madK thanks for posting the file and your steps.

When following them I get another error, which I have not encountered so far (have not used the kickstart feature while building):

```
-> Building installer-qubes-os iso for fc32
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pykickstart/load.py", line 93, in _load_file
    with open(filename, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/qubes-builder/qubes-src/installer-qubes-os/conf/iso-full-online.ks'
```

Whereas the file exists with proper permissions and the meta links in the file are reachable.
```
[user@qubes-make qubes-builder]$ ls -lha /home/user/qubes-builder/qubes-src/installer-qubes-os/conf/
-rw-rw-r--  2 user user  766 Mar  3 13:22 iso-full-online.ks
-rw-rw-r--  2 user user 2.0K Mar  3 13:22 qubes-kickstart.cfg
```

```
[user@qubes-make qubes-builder]$ cat /home/user/qubes-builder/qubes-src/installer-qubes-os/conf/iso-full-online.ks
# Full ISO build using packages from online repositories instead of local build
%include qubes-kickstart.cfg

repo --name=qubes-r4.1 --gpgkey=file:///tmp/qubes-installer/qubes-release/RPM-GPG-KEY-qubes-4.1-primary --baseurl=http://yum.qubes-os.org/r4.1/current-testing/dom0/fc32 --ignoregroups=true
repo --name=qubes-r4.1-templates-itl --gpgkey=file:///tmp/qubes-installer/qubes-release/RPM-GPG-KEY-qubes-4.1-primary --metalink=http://yum.qubes-os.org/r4.1/templates-itl/repodata/repomd.xml.metalink --ignoregroups=true
repo --name=qubes-r4.1-templates-community --gpgkey=file:///tmp/qubes-installer/qubes-release/RPM-GPG-KEY-qubes-4.1-templates-community --metalink=http://yum.qubes-os.org/r4.1/templates-community/repodata/repomd.xml.metalink --ignoregroups=true
```
Any idea what could be the issue there?
Will go for a full offline build in the meanwhile.

**Comment by marmarek** [comment]
> '/home/user/qubes-builder/qubes-src/installer-qubes-os/conf/iso-full-online.ks'

This should be `/home/user/qubes-src/installer-qubes-os/conf/iso-full-online.ks` (without `qubes-builder` part). The path is resolved inside chroot env used to build and so it is `/home/user/qubes-src` regardless of where you keep your sources.

**Comment by tweidinger** [comment]
@marmarek thanks! I feel a bit stupid now re-reading my question :see_no_evil: 

Fixes the error and builds the iso. Hope it will make qubes usable on my device.

**Comment by tweidinger** [comment]
Still picks up the upstream kernel instead of local :disappointed: 
@n0madK could you please verify that this matches your approach? Thanks :blush: 

clone qubes-builder
use builder.conf from above and add the xen branch, use master for linux kernel.

```
BRANCH_linux_kernel = master
BRANCH_vmm_xen = xen-4.14
```

```
make install-deps
make get-sources
make qubes
cd qubes-src/linux-kernel
git branch -m stable-5.10
git reset --hard stable-5.10
```

remove `%define name_suffix -latest` from `qubes-src/linux-kernel/kernel.spec.in`
Go back into the builder directory and replace the kernel branch with

`
BRANCH_linux_kernel = stable-5.10
`

```
make linux-kernel
make iso
```

**Comment by EvTheFuture** [comment]
> @n0madK could you please verify that this matches your approach? Thanks 😊

Good question. I'm also struggling and are curious on how to get it to include the "right" kernel.

**Comment by n0madK** [comment]
I did a couple of builds to test and it seems the important point are in the last few steps:

- make sure the builder.conf `BRANCH_linux_kernel` matches your local branch name for qubes-src/linux-kernel
- in qubes-src/linux-kernel, this line must be removed, not just commented
```
diff --git a/kernel.spec.in b/kernel.spec.in
index 55f7b19..5e50b47 100644
--- a/kernel.spec.in
+++ b/kernel.spec.in
@@ -15,8 +15,6 @@
 %define rel %{plainrel}.%{variant}
 %endif
 
-%define name_suffix -latest
-
 %define _buildshell /bin/bash
 %define build_xen       1
 ```
- build the kernel, and make sure that the artifact exists without the `-latest` tag
```
make linux-kernel
ls qubes-src/linux-kernel/pkgs/dom0-fc32/x86_64/
```
should have something like `kernel-5.10.16-1.3.fc32.qubes.x86_64.rpm` or whatever kernel you're branch is on
- build the iso
```
make iso
```


You should see it pickup your kernel package in the package list output fairly early on. So you can see if it will work before downloading 3GB of packages.
```
-> Building installer-qubes-os iso for fc32
...
kernel                                         x86_64          1000:5.10.16-1.3.fc32.qubes                  qubes-dom0               63 M
kernel-qubes-vm                                x86_64          1000:5.10.16-1.3.fc32.qubes                  qubes-dom0               96 M
 ```

**Comment by EvTheFuture** [comment]
> in qubes-src/linux-kernel, this line must be removed, not just commented

Oh, this is a mistake I know I made. I'll try again with these clarifications. Thank you!

**Comment by tweidinger** [comment]
Can confirm it picks up the correct kernel! Thanks @n0madK :smile:

**Comment by n0madK** [comment]
@tweidinger do you mean that it crashes and reboots when sys-net/sys-usb starts? I ended installing with kernel 5.8.16-1 due to this problem. It was resolved for me in 5.10.16-1.3 https://github.com/QubesOS/qubes-issues/issues/6397#issuecomment-789742589

**Comment by tweidinger** [comment]
@n0madK no I am not even getting to starting other vms. My device gets stuck even before setting up dom0 properly. I suspect some issues on the xen side for my hardware (Ryzen 4800H + RTX 2060). It just hangs in a soft stuck loop or just hard stucks while enumerating pci devices.

Should I open another issue for this?

![soft_stuck_xen_pci](https://user-images.githubusercontent.com/28728469/110307611-69011a00-7fff-11eb-8a37-0197123e79c7.png)

![bar_6](https://user-images.githubusercontent.com/28728469/110307659-76b69f80-7fff-11eb-8f9c-b5c80b9d55b9.jpeg)

**Comment by n0madK** [comment]
I have the "RIP xen_hypercall_xen_version ryzen" in my search history, but I don't recall what I did to fix that. IIRC I just slowly rolled back from 5.10.x to 5.9.x before landing on 5.8.16 which finally worked. The version you're using (5.10.16-1) did not work from installer or dom0, but 5.10.16-1.3 works in dom0. The fixes in 5.10.16-1.3 are also supposed to be in 5.10.21 and 5.11.4 also.

**Comment by tweidinger** [comment]
Will try other kernel versions but 5.8.16-1 did not work on my system. It hangs at the same output (2 out of 3 times without displaying a soft lockup, just freezing completely).

**Comment by EvTheFuture** [comment]
I can confirm building with kernel 5.10 and Xen 4.14 per @n0madK instructions got a working iso for me. It successfully boots and I can install on local disk.

Have not tested to boot installed version yet.

Lenovo L14 gen1 (Ryzen 4500U)

**Comment by tasket** [comment]
For others who installed from a local build of R4.1 alpha and may be having the same problem, here is my experience:

After successfully installing with dom0 kernel 5.8.5, kernel updates only worked until 5.8.16-200. Everything after that was coming down as 5.9, 5.10 and 5.11 and failing to boot (with the "not an ELF binary" error msg)... I was stuck on kernel 5.8.16.

Catching up with this issue, I realized something was amiss; apparently kernel updates were __still__ coming with the incorrect compression format. Yet there were indications from Marek and other posters that this already had been addressed.

Investigating further, I was getting updates via "kernel-core" package, but "kernel" package was not installed! When I manually installed "kernel" I got the 5.10.28-1 version from testing, which now boots and appears to work properly.

---

Since this issue is Ryzen-themed (perhaps incidentally), I must mention the brilliant workaround that was posted for recent AMD Thinkpads that resolved several odd behaviors and errors (incl. sys-usb intermittent failure and KDE startup problems): https://github.com/QubesOS/qubes-issues/issues/6055#issuecomment-799823559

Only two issues remain:

 * Sleep/wake not working
 * Using internal Intel Ax200 wifi causes system instability, issue #6564

**Comment by DemiMarie** [comment]
@Tie-fighter I can’t help technically, but I can say awesome username.

**Comment by fepitre** [comment]
@Tie-fighter try with weekly build signed ISOs (see https://qubes-os.discourse.group/t/qubesos-4-1-alpha-signed-weekly-builds/3601): https://qubes.notset.fr/iso/ you have both standard ISO with LTS kernel (currently 5.10) and with `kernel-latest` in both anaconda and installed Qubes (currently 5.12)

**Comment by Tie-fighter** [comment]
> @Tie-fighter try with weekly build signed ISOs (see https://qubes-os.discourse.group/t/qubesos-4-1-alpha-signed-weekly-builds/3601): https://qubes.notset.fr/iso/ you have both standard ISO with LTS kernel (currently 5.10) and with `kernel-latest` in both anaconda and installed Qubes (currently 5.12)

Qubes-20210612-x86_64 using Rufus in dd mode worked :)
