### ISSUE TITLE
sys-gui and sys-gui-vm won't boot in 4.1 with error no such file usr/bin/qubes-input-trigger --all 

### ISSUE THREAD

**Issue by face** [QubesOS/qubes-issues#6789]
- 

### Qubes OS version

R4.1

### Which [testing](https://www.qubes-os.org/doc/testing/) repositories are you using, if any?

 - qubes-dom0-security-testing
 - qubes-dom0-current-testing
 - qubes-templates-itl-testing
 - qubes-templates-community
 - qubes-templates-community-testing

### Are you providing feedback about a specific package or packages in testing?

Testing sys-gui-gpu

### Affected component(s) or functionality

sys-gui and sys-gui-gpu.     The bug is in qubes-core-admin.

-----
### Brief summary

`sys-gui` and `sys-gui-gpu` both fail to boot with the error:  `no such file or directory /usr/bin/qubes-input-trigger --all --dom0 failed with erno2`

Reported here https://forum.qubes-os.org/t/how-to-enable-the-new-gui-vm/2631/7

### How reproducible

100%

### Steps to reproduce

```
qubesctl top.enable qvm.sys-gui
qubesctl top.enable qvm.sys-gui pillar=True
qubesctl --all state.highstate
```

sys-gui-gpu will not boot and the salt script will fail.

### Expected behavior

sys-gui-gpu or sys-gui will be correctly configured.

### Actual behavior

sys-gui will not boot during salt scripts, and then essential services will not get installed.    salt will not detect this so the vm must be deleted to salt can correctly complete the enable configuration.

### Solutions you've tried

I fixed the code:  https://github.com/QubesOS/qubes-core-admin/pull/415

### Additional context

Multiple people have run into this in different threads in the forum..here is the first one I came accross:  https://forum.qubes-os.org/t/how-to-enable-the-new-gui-vm/2631/7

-----

**Comment by ydirson** [comment]
Nice to see this is fixed in testing!  What packages should we pull from testing to get the fix ?

**Comment by andrewdavidwong** [comment]
Changing "diagnosed" to "needs diagnosis" based on report in #6893 that the bug persists even after https://github.com/QubesOS/qubes-core-admin/pull/415.

**Comment by marmarek** [comment]
Is `qubes-input-proxy-sender` package installed in dom0?

**Comment by andrewdavidwong** [comment]
> Changing "diagnosed" to "needs diagnosis" based on report in #6893 that the bug persists even after [QubesOS/qubes-core-admin#415](https://github.com/QubesOS/qubes-core-admin/pull/415).

Undoing this, as @ydirson insists that #6893 is not really a duplicate.

**Comment by ydirson** [comment]
> Is `qubes-input-proxy-sender` package installed in dom0?

Probbly not :)

However I'll be able to answer only after recovering -- see https://forum.qubes-os.org/t/disabling-sys-gui-gpu-from-commandline/6288, I have hacked around the missing script to see how far it would do (symlinking to `/bin/true` or `/bin/false` allowed to proceed with the installation, without one making a difference on the other).  Currently trying to find a boot media that will allow me to run `qubes-prefs`...

**Comment by marmarek** [comment]
Fixed in https://github.com/QubesOS/qubes-core-admin/pull/415
