### ISSUE TITLE
sudo xl list -l <domain_id> fails with libxl error for stubdomains - maybe upstream issue?

### ISSUE THREAD

**Issue by brendanhoar** [QubesOS/qubes-issues#7175]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1rc2 updated to R4.1rc3 (w/ current-testing)

### Brief summary
sudo xl list -l <domain_id> should provide information about a currently running domain. It works for 0 (dom0) but not for some/all other domains.

### Steps to reproduce
```
sudo xl list # to get list of ids # 0 was dom0, 1 was sys-usb, 2 was sys-usb-dm, 3 was sys-net, 4 was sys-net-dm, 5 was sys-firewall, 6 was untrusted
sudo xl list -l 0 # to get dom0 info, which works
sudo xl list -l 1 # to get sys-usb domain info, which fails with error for HVM
sudo xl list -l 2 # to get sys-usb's stub domain info, which fails error for stub domain 
sudo xl list -l 3 # to get sys-net domain info, which fails with error for HVM
sudo xl list -l 4 # to get sys-net's stub domain info, which fails error for stub domain
sudo xl list -l 5 # to get sys-firewall's info
sudo xl list -l 6 # to get untrusted's info
```

### Expected behavior
JSON object with dom0 data
JSON object with sys-usb data
JSON object with sys-usb-dm data
JSON object with sys-net data
JSON object with sys-net-dm data
JSON object with sys-firewall data
JSON object with untrusted data

### Actual behavior
JSON object with dom0 data
libxl: error: libxl_qmp.c:1836:qmp_ev_parse_error_messages: Domain 1:The command query-cpus has not been found
libxl: error: libxl_domain.c:2178:retreive_domain_configuration_lock_acquired: Domain 2:Fail to get domain configuration
libxl: error: libxl_qmp.c:1836:qmp_ev_parse_error_messages: Domain 3:The command query-cpus has not been found
libxl: error: libxl_domain.c:2178:retreive_domain_configuration_lock_acquired: Domain 4:Fail to get domain configuration
JSON object with sys-firewall data
JSON object with untrusted data

Thanks,
Brendan

**Comment by marmarek** [comment]
Just to confirm - do you have `xen-hvm-stubdom-linux` 1.2.0 or 1.2.1? I guess the latter.

**Comment by brendanhoar** [comment]
For R4.1, yes, the error messages above are with xen-hvm-stubdom-linux 1.2.1.

Just for reference, under *R4.0* it's also broken for both HVM and stubdom
HVM:
```
[admin@dom0 ~]$ sudo xl list -l 237
libxl: error: libxl_qmp.c:702:libxl__qmp_initialize: Connection error: No such file or directory
libxl: error: libxl.c:6767:libxl__update_avail_vcpus_qmp: fail to get number of cpus for domain 237
libxl: error: libxl.c:6890:libxl_retrieve_domain_configuration: fail to update available cpu map for domain 237
[

]
```
stubdom:
```
[admin@dom0 ~]$ sudo xl list -l 238
libxl: error: libxl.c:6821:libxl_retrieve_domain_configuration: fail to get domain configuration for domain 238
[

]
```

**Comment by marmarek** [comment]
> For R4.1, yes, the error messages above are with xen-hvm-stubdom-linux 1.2.1.

Linked PR should fix it.

> PS - I also ran across this old, likely related thread on xen-devel which may be familiar to you: https://patchew.org/Xen/20191112141943.245215-1-anthony.perard@citrix.com/

We have this already in R4.1, and it isn't relevant for R4.0. It fails on R4.0 because we don't have full communication with QEMU there (although this particular case probably could be patched out).

**Comment by brendanhoar** [comment]
> > For R4.1, yes, the error messages above are with xen-hvm-stubdom-linux 1.2.1.
> 
> Linked PR should fix it.

Thanks Marek. I can confirm that the fixed worked for the HVM issue.

However, the stubdoms still fail with an error:

libxl: error: libxl_domain.c:2247:retreive_domain_configuration_lock_acquired: Domain 2:Fail to get domain configuration

So, right now, I don't really have a way to examine the runtime properties of stubdomains via xl (due to this message) or virsh (which doesn't support them).

Any alternate ways to get the info (e.g. virtual machine type)?

Thanks,
Brendan

**Comment by DemiMarie** [comment]
Reopening to track the stubdomain problem.

**Comment by marmarek** [comment]
> However, the stubdoms still fail with an error:

That is expected, stubdomain does not have its own config etc, logically it's part of its target domain. Anyway, at this point it isn't anything qubes specific, that's how Xen works.

**Comment by brendanhoar** [comment]
Thanks.

I disagree that it's "expected" that ```xl list <stubdomid>``` should work, while ```xl list --long <stubdomid``` should throw an unexpected error.

With that said, however, I fully agree it is an upstream Xen issue. As Qubes has no need for the functionality, it should not be addressed here and I agree with closing the issue**.

Thanks for all you do!
Brendan

**not that you needed or wanted permission, of course. :)

**Comment by DemiMarie** [comment]
Marked as “not our bug” because this is an upstream Xen issue, not a Qubes issue.  Feel free to report it to the Xen developers.

**Comment by andrewdavidwong** [comment]
> Marked as “not our bug” because this is an upstream Xen issue, not a Qubes issue.  Feel free to report it to the Xen developers.

Well, the original one was, though. It's just the attempted follow-up that wasn't. But I suppose this is fine.
