### ISSUE TITLE
Attempting to update dom0 for QSB-078 results in package errors

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#7336]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.0

### Brief summary

Update dom0 for [QSB-078](https://www.qubes-os.org/news/2022/03/10/qsb-078/).

### Steps to reproduce

Perform a normal update with the `security-testing` repo enabled.

### Expected behavior

Normal successful update.

### Actual behavior

Errors encountered:

```
$ sudo qubesctl --show-output state.sls update.qubes-dom0
[ERROR   ] Command '['systemd-run', '--scope', 'qubes-dom0-update', '--quiet', '-y', '--clean', '--action=upgrade']' failed with return code: 1
[ERROR   ] stderr: Running scope as unit: run-r1018b74ec3e44f169d21dae9da7b37d7.scope
Using sys-update as UpdateVM to download updates for Dom0; this may take some time...
warning: Converting database from bdb_ro to sqlite backend
Importing GPG key 0x9E2795E9:
 Userid     : "Qubes OS Release 4 Signing Key"
 Fingerprint: 5817 A43B 283D E5A9 181A 522E 1848 792F 9E27 95E9
 From       : /var/lib/qubes/dom0-updates/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary
Importing GPG key 0x9E2795E9:
 Userid     : "Qubes OS Release 4 Signing Key"
 Fingerprint: 5817 A43B 283D E5A9 181A 522E 1848 792F 9E27 95E9
 From       : /var/lib/qubes/dom0-updates/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary
Importing GPG key 0x9E2795E9:
 Userid     : "Qubes OS Release 4 Signing Key"
 Fingerprint: 5817 A43B 283D E5A9 181A 522E 1848 792F 9E27 95E9
 From       : /var/lib/qubes/dom0-updates/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary
Error: 
 Problem 1: problem with installed package lvm2-python-libs-2.02.167-3.fc25.x86_64
  - cannot install the best update candidate for package lvm2-python-libs-2.02.167-3.fc25.x86_64
  - nothing provides lvm2-libs = 2.02.167-4.fc25 needed by lvm2-python-libs-1:2.02.167-4.fc25.x86_64
 Problem 2: problem with installed package lvm2-libs-2.02.167-3.fc25.x86_64
  - cannot install the best update candidate for package lvm2-libs-2.02.167-3.fc25.x86_64
  - nothing provides device-mapper-event = 1.02.136-4.fc25 needed by lvm2-libs-1:2.02.167-4.fc25.x86_64
 Problem 3: problem with installed package lvm2-2.02.167-3.fc25.x86_64
  - cannot install the best update candidate for package lvm2-2.02.167-3.fc25.x86_64
  - nothing provides lvm2-libs = 2.02.167-4.fc25 needed by lvm2-1:2.02.167-4.fc25.x86_64
 Problem 4: problem with installed package device-mapper-libs-1.02.136-3.fc25.x86_64
  - cannot install the best update candidate for package device-mapper-libs-1.02.136-3.fc25.x86_64
  - nothing provides device-mapper = 1.02.136-4.fc25 needed by device-mapper-libs-1:1.02.136-4.fc25.x86_64
 Problem 5: problem with installed package device-mapper-event-1.02.136-3.fc25.x86_64
  - cannot install the best update candidate for package device-mapper-event-1.02.136-3.fc25.x86_64
  - nothing provides device-mapper = 1.02.136-4.fc25 needed by device-mapper-event-1:1.02.136-4.fc25.x86_64
  - nothing provides device-mapper-event-libs = 1.02.136-4.fc25 needed by device-mapper-event-1:1.02.136-4.fc25.x86_64
 Problem 6: problem with installed package device-mapper-1.02.136-3.fc25.x86_64
  - cannot install the best update candidate for package device-mapper-1.02.136-3.fc25.x86_64
  - nothing provides device-mapper-libs = 1.02.136-4.fc25 needed by device-mapper-1:1.02.136-4.fc25.x86_64
 Problem 7: problem with installed package device-mapper-event-libs-1.02.136-3.fc25.x86_64
  - cannot install the best update candidate for package device-mapper-event-libs-1.02.136-3.fc25.x86_64
  - problem with installed package kernel-qubes-vm-1000:5.4.143-1.fc25.qubes.x86_64
  - cannot install the best update candidate for package kernel-qubes-vm-1000:5.4.143-1.fc25.qubes.x86_64
  - package kernel-qubes-vm-1000:5.4.143-1.fc25.qubes.x86_64 requires qubes-core-dom0, but none of the providers can be installed
  - package kernel-qubes-vm-1000:5.4.183-2.fc25.qubes.x86_64 requires qubes-core-dom0, but none of the providers can be installed
  - package qubes-core-dom0-4.0.59-1.fc25.x86_64 requires libvirt-daemon-xen >= 3.3.0-10, but none of the providers can be installed
  - package qubes-core-dom0-4.0.58-1.fc25.x86_64 requires libvirt-daemon-xen >= 3.3.0-10, but none of the providers can be installed
  - package libvirt-daemon-xen-3.3.0-10.fc25.x86_64 requires libvirt-daemon-driver-storage = 3.3.0-10.fc25, but none of the providers can be installed
  - package libvirt-daemon-driver-storage-3.3.0-10.fc25.x86_64 requires libvirt-daemon-driver-storage-logical = 3.3.0-10.fc25, but none of the providers can be installed
  - package libvirt-daemon-driver-storage-logical-3.3.0-10.fc25.x86_64 requires lvm2, but none of the providers can be installed
  - package lvm2-2.02.167-3.fc25.x86_64 requires liblvm2app.so.2.2()(64bit), but none of the providers can be installed
  - package lvm2-2.02.167-3.fc25.x86_64 requires liblvm2app.so.2.2(Base)(64bit), but none of the providers can be installed
  - package lvm2-libs-2.02.167-3.fc25.x86_64 requires device-mapper-event = 1.02.136-3.fc25, but none of the providers can be installed
  - package device-mapper-event-1.02.136-3.fc25.x86_64 requires device-mapper-event-libs = 1.02.136-3.fc25, but none of the providers can be installed
  - device-mapper-event-libs-1.02.136-3.fc25.i686 has inferior architecture
  - cannot install both device-mapper-event-libs-1:1.02.136-4.fc25.x86_64 and device-mapper-event-libs-1.02.136-3.fc25.x86_64
  - cannot install the best update candidate for package lvm2-2.02.167-3.fc25.x86_64
  - cannot install the best update candidate for package lvm2-libs-2.02.167-3.fc25.x86_64
  - nothing provides lvm2-libs = 2.02.167-4.fc25 needed by lvm2-1:2.02.167-4.fc25.x86_64
  - nothing provides device-mapper-event = 1.02.136-4.fc25 needed by lvm2-libs-1:2.02.167-4.fc25.x86_64
[ERROR   ] retcode: 1
[ERROR   ] Problem encountered upgrading packages. Additional info follows:

result:
    ----------
    pid:
        26146
    retcode:
        1
    stderr:
        Running scope as unit: run-r1018b74ec3e44f169d21dae9da7b37d7.scope
        Using sys-update as UpdateVM to download updates for Dom0; this may take some time...
        warning: Converting database from bdb_ro to sqlite backend
        Importing GPG key 0x9E2795E9:
         Userid     : "Qubes OS Release 4 Signing Key"
         Fingerprint: 5817 A43B 283D E5A9 181A 522E 1848 792F 9E27 95E9
         From       : /var/lib/qubes/dom0-updates/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary
        Importing GPG key 0x9E2795E9:
         Userid     : "Qubes OS Release 4 Signing Key"
         Fingerprint: 5817 A43B 283D E5A9 181A 522E 1848 792F 9E27 95E9
         From       : /var/lib/qubes/dom0-updates/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary
        Importing GPG key 0x9E2795E9:
         Userid     : "Qubes OS Release 4 Signing Key"
         Fingerprint: 5817 A43B 283D E5A9 181A 522E 1848 792F 9E27 95E9
         From       : /var/lib/qubes/dom0-updates/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary
        Error: 
         Problem 1: problem with installed package lvm2-python-libs-2.02.167-3.fc25.x86_64
          - cannot install the best update candidate for package lvm2-python-libs-2.02.167-3.fc25.x86_64
          - nothing provides lvm2-libs = 2.02.167-4.fc25 needed by lvm2-python-libs-1:2.02.167-4.fc25.x86_64
         Problem 2: problem with installed package lvm2-libs-2.02.167-3.fc25.x86_64
          - cannot install the best update candidate for package lvm2-libs-2.02.167-3.fc25.x86_64
          - nothing provides device-mapper-event = 1.02.136-4.fc25 needed by lvm2-libs-1:2.02.167-4.fc25.x86_64
         Problem 3: problem with installed package lvm2-2.02.167-3.fc25.x86_64
          - cannot install the best update candidate for package lvm2-2.02.167-3.fc25.x86_64
          - nothing provides lvm2-libs = 2.02.167-4.fc25 needed by lvm2-1:2.02.167-4.fc25.x86_64
         Problem 4: problem with installed package device-mapper-libs-1.02.136-3.fc25.x86_64
          - cannot install the best update candidate for package device-mapper-libs-1.02.136-3.fc25.x86_64
          - nothing provides device-mapper = 1.02.136-4.fc25 needed by device-mapper-libs-1:1.02.136-4.fc25.x86_64
         Problem 5: problem with installed package device-mapper-event-1.02.136-3.fc25.x86_64
          - cannot install the best update candidate for package device-mapper-event-1.02.136-3.fc25.x86_64
          - nothing provides device-mapper = 1.02.136-4.fc25 needed by device-mapper-event-1:1.02.136-4.fc25.x86_64
          - nothing provides device-mapper-event-libs = 1.02.136-4.fc25 needed by device-mapper-event-1:1.02.136-4.fc25.x86_64
         Problem 6: problem with installed package device-mapper-1.02.136-3.fc25.x86_64
          - cannot install the best update candidate for package device-mapper-1.02.136-3.fc25.x86_64
          - nothing provides device-mapper-libs = 1.02.136-4.fc25 needed by device-mapper-1:1.02.136-4.fc25.x86_64
         Problem 7: problem with installed package device-mapper-event-libs-1.02.136-3.fc25.x86_64
          - cannot install the best update candidate for package device-mapper-event-libs-1.02.136-3.fc25.x86_64
          - problem with installed package kernel-qubes-vm-1000:5.4.143-1.fc25.qubes.x86_64
          - cannot install the best update candidate for package kernel-qubes-vm-1000:5.4.143-1.fc25.qubes.x86_64
          - package kernel-qubes-vm-1000:5.4.143-1.fc25.qubes.x86_64 requires qubes-core-dom0, but none of the providers can be installed
          - package kernel-qubes-vm-1000:5.4.183-2.fc25.qubes.x86_64 requires qubes-core-dom0, but none of the providers can be installed
          - package qubes-core-dom0-4.0.59-1.fc25.x86_64 requires libvirt-daemon-xen >= 3.3.0-10, but none of the providers can be installed
          - package qubes-core-dom0-4.0.58-1.fc25.x86_64 requires libvirt-daemon-xen >= 3.3.0-10, but none of the providers can be installed
          - package libvirt-daemon-xen-3.3.0-10.fc25.x86_64 requires libvirt-daemon-driver-storage = 3.3.0-10.fc25, but none of the providers can be installed
          - package libvirt-daemon-driver-storage-3.3.0-10.fc25.x86_64 requires libvirt-daemon-driver-storage-logical = 3.3.0-10.fc25, but none of the providers can be installed
          - package libvirt-daemon-driver-storage-logical-3.3.0-10.fc25.x86_64 requires lvm2, but none of the providers can be installed
          - package lvm2-2.02.167-3.fc25.x86_64 requires liblvm2app.so.2.2()(64bit), but none of the providers can be installed
          - package lvm2-2.02.167-3.fc25.x86_64 requires liblvm2app.so.2.2(Base)(64bit), but none of the providers can be installed
          - package lvm2-libs-2.02.167-3.fc25.x86_64 requires device-mapper-event = 1.02.136-3.fc25, but none of the providers can be installed
          - package device-mapper-event-1.02.136-3.fc25.x86_64 requires device-mapper-event-libs = 1.02.136-3.fc25, but none of the providers can be installed
          - device-mapper-event-libs-1.02.136-3.fc25.i686 has inferior architecture
          - cannot install both device-mapper-event-libs-1:1.02.136-4.fc25.x86_64 and device-mapper-event-libs-1.02.136-3.fc25.x86_64
          - cannot install the best update candidate for package lvm2-2.02.167-3.fc25.x86_64
          - cannot install the best update candidate for package lvm2-libs-2.02.167-3.fc25.x86_64
          - nothing provides lvm2-libs = 2.02.167-4.fc25 needed by lvm2-1:2.02.167-4.fc25.x86_64
          - nothing provides device-mapper-event = 1.02.136-4.fc25 needed by lvm2-libs-1:2.02.167-4.fc25.x86_64
    stdout:
local:
----------
          ID: /etc/yum.repos.d/qubes-dom0.repo
    Function: file.replace
      Result: True
     Comment: No changes needed to be made
     Started: 14:10:57.697814
    Duration: 5.852 ms
     Changes:   
----------
          ID: /etc/yum.repos.d/qubes-templates.repo
    Function: file.replace
      Result: True
     Comment: No changes needed to be made
     Started: 14:10:57.703769
    Duration: 1.094 ms
     Changes:   
----------
          ID: update
    Function: pkg.uptodate
      Result: False
     Comment: Problem encountered upgrading packages. Additional info follows:
              
              result:
                  ----------
                  pid:
                      26146
                  retcode:
                      1
                  stderr:
                      Running scope as unit: run-r1018b74ec3e44f169d21dae9da7b37d7.scope
                      Using sys-update as UpdateVM to download updates for Dom0; this may take some time...
                      warning: Converting database from bdb_ro to sqlite backend
                      Importing GPG key 0x9E2795E9:
                       Userid     : "Qubes OS Release 4 Signing Key"
                       Fingerprint: 5817 A43B 283D E5A9 181A 522E 1848 792F 9E27 95E9
                       From       : /var/lib/qubes/dom0-updates/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary
                      Importing GPG key 0x9E2795E9:
                       Userid     : "Qubes OS Release 4 Signing Key"
                       Fingerprint: 5817 A43B 283D E5A9 181A 522E 1848 792F 9E27 95E9
                       From       : /var/lib/qubes/dom0-updates/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary
                      Importing GPG key 0x9E2795E9:
                       Userid     : "Qubes OS Release 4 Signing Key"
                       Fingerprint: 5817 A43B 283D E5A9 181A 522E 1848 792F 9E27 95E9
                       From       : /var/lib/qubes/dom0-updates/etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4.0-primary
                      Error: 
                       Problem 1: problem with installed package lvm2-python-libs-2.02.167-3.fc25.x86_64
                        - cannot install the best update candidate for package lvm2-python-libs-2.02.167-3.fc25.x86_64
                        - nothing provides lvm2-libs = 2.02.167-4.fc25 needed by lvm2-python-libs-1:2.02.167-4.fc25.x86_64
                       Problem 2: problem with installed package lvm2-libs-2.02.167-3.fc25.x86_64
                        - cannot install the best update candidate for package lvm2-libs-2.02.167-3.fc25.x86_64
                        - nothing provides device-mapper-event = 1.02.136-4.fc25 needed by lvm2-libs-1:2.02.167-4.fc25.x86_64
                       Problem 3: problem with installed package lvm2-2.02.167-3.fc25.x86_64
                        - cannot install the best update candidate for package lvm2-2.02.167-3.fc25.x86_64
                        - nothing provides lvm2-libs = 2.02.167-4.fc25 needed by lvm2-1:2.02.167-4.fc25.x86_64
                       Problem 4: problem with installed package device-mapper-libs-1.02.136-3.fc25.x86_64
                        - cannot install the best update candidate for package device-mapper-libs-1.02.136-3.fc25.x86_64
                        - nothing provides device-mapper = 1.02.136-4.fc25 needed by device-mapper-libs-1:1.02.136-4.fc25.x86_64
                       Problem 5: problem with installed package device-mapper-event-1.02.136-3.fc25.x86_64
                        - cannot install the best update candidate for package device-mapper-event-1.02.136-3.fc25.x86_64
                        - nothing provides device-mapper = 1.02.136-4.fc25 needed by device-mapper-event-1:1.02.136-4.fc25.x86_64
                        - nothing provides device-mapper-event-libs = 1.02.136-4.fc25 needed by device-mapper-event-1:1.02.136-4.fc25.x86_64
                       Problem 6: problem with installed package device-mapper-1.02.136-3.fc25.x86_64
                        - cannot install the best update candidate for package device-mapper-1.02.136-3.fc25.x86_64
                        - nothing provides device-mapper-libs = 1.02.136-4.fc25 needed by device-mapper-1:1.02.136-4.fc25.x86_64
                       Problem 7: problem with installed package device-mapper-event-libs-1.02.136-3.fc25.x86_64
                        - cannot install the best update candidate for package device-mapper-event-libs-1.02.136-3.fc25.x86_64
                        - problem with installed package kernel-qubes-vm-1000:5.4.143-1.fc25.qubes.x86_64
                        - cannot install the best update candidate for package kernel-qubes-vm-1000:5.4.143-1.fc25.qubes.x86_64
                        - package kernel-qubes-vm-1000:5.4.143-1.fc25.qubes.x86_64 requires qubes-core-dom0, but none of the providers can be installed
                        - package kernel-qubes-vm-1000:5.4.183-2.fc25.qubes.x86_64 requires qubes-core-dom0, but none of the providers can be installed
                        - package qubes-core-dom0-4.0.59-1.fc25.x86_64 requires libvirt-daemon-xen >= 3.3.0-10, but none of the providers can be installed
                        - package qubes-core-dom0-4.0.58-1.fc25.x86_64 requires libvirt-daemon-xen >= 3.3.0-10, but none of the providers can be installed
                        - package libvirt-daemon-xen-3.3.0-10.fc25.x86_64 requires libvirt-daemon-driver-storage = 3.3.0-10.fc25, but none of the providers can be installed
                        - package libvirt-daemon-driver-storage-3.3.0-10.fc25.x86_64 requires libvirt-daemon-driver-storage-logical = 3.3.0-10.fc25, but none of the providers can be installed
                        - package libvirt-daemon-driver-storage-logical-3.3.0-10.fc25.x86_64 requires lvm2, but none of the providers can be installed
                        - package lvm2-2.02.167-3.fc25.x86_64 requires liblvm2app.so.2.2()(64bit), but none of the providers can be installed
                        - package lvm2-2.02.167-3.fc25.x86_64 requires liblvm2app.so.2.2(Base)(64bit), but none of the providers can be installed
                        - package lvm2-libs-2.02.167-3.fc25.x86_64 requires device-mapper-event = 1.02.136-3.fc25, but none of the providers can be installed
                        - package device-mapper-event-1.02.136-3.fc25.x86_64 requires device-mapper-event-libs = 1.02.136-3.fc25, but none of the providers can be installed
                        - device-mapper-event-libs-1.02.136-3.fc25.i686 has inferior architecture
                        - cannot install both device-mapper-event-libs-1:1.02.136-4.fc25.x86_64 and device-mapper-event-libs-1.02.136-3.fc25.x86_64
                        - cannot install the best update candidate for package lvm2-2.02.167-3.fc25.x86_64
                        - cannot install the best update candidate for package lvm2-libs-2.02.167-3.fc25.x86_64
                        - nothing provides lvm2-libs = 2.02.167-4.fc25 needed by lvm2-1:2.02.167-4.fc25.x86_64
                        - nothing provides device-mapper-event = 1.02.136-4.fc25 needed by lvm2-libs-1:2.02.167-4.fc25.x86_64
                  stdout:
     Started: 14:10:58.222324
    Duration: 801840.241 ms
     Changes:   

Summary for local
------------
Succeeded: 2
Failed:    1
------------
Total states run:     3
Total run time: 801.847 s
DOM0 configuration failed, not continuing
```

**Comment by marmarek** [comment]
Fixed in https://github.com/QubesOS/updates-status/issues/2863

**Comment by TNTBOMBOM** [comment]
Does this as well suppose to fix: 

`warning: Converting database from bdb_ro to sqlite backend`

or this is expected, fine to have? (still happening)

**Comment by marmarek** [comment]
> `warning: Converting database from bdb_ro to sqlite backend`

This one is expected and harmless.
