### ISSUE TITLE
The horizontal resize (shrinking) of Xfce settings window is not working because icons refuse to be wrapped.

### ISSUE THREAD

**Issue by jamke** [QubesOS/qubes-issues#7888]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1.1.

### Brief summary
The horizontal resize (shrinking) of Xfce settings window is not working because icons refuse to be wrapped.

### Steps to reproduce
1. Open `System Tools` -> `Settings Manager`.
2. Try to make it smaller horizontally (narrow)

### Expected behavior 
The window becomes smaller (narrower).

### Actual behavior
When right side of the window reaches any icon inside - the resizing stops.

### More
1) Making the window wider works, but still every time I make the window bigger by resizing - the minimal width I can set increases until all icons are on one line unwrapped.

2) I understand that Xfce is not good with stability in general, but I doubt they have such UX bug upstream. On the other hand it's xfce, so it can be their bug in the first place.

**Comment by andrewdavidwong** [comment]
> Making the window wider works, but still every time I make the window bigger by resizing - the minimal width I can set increases until all icons are on one line unwrapped.

I can reproduce the described behavior and agree it is a bug.

> I understand that Xfce is not good with stability in general, but I doubt they have such UX bug upstream. On the other hand it's xfce, so it can be their bug in the first place.

I, too, wonder whether this bug exists upstream (e.g., in baremetal Fedora with Xfce4). If anyone reading this is able to check that, please do let us know.

**Comment by jamke** [comment]
@unman 
Can you please give a link to this bug?
I did not have this "feature" on Qubes OS R4.0 if I am not mistaken.

**Comment by jamke** [comment]
I found it, it's just an another bug of **xfce**.
https://bugzilla.xfce.org/show_bug.cgi?id=16276
https://bugzilla.xfce.org/show_bug.cgi?id=16028
It was fixed in 2020.

I think this issue should be closed as `not our bug`.
And maybe someday the fix will get to Qubes OS.

**Comment by DemiMarie** [comment]
Reopening, as “not our bug” is for bugs not yet fixed upstream.  In this case, the problem _has_ been fixed upstream, but dom0 has an old version that still has the bug.

**Comment by andrewdavidwong** [comment]
> Reopening, as “not our bug” is for bugs not yet fixed upstream.

Technically, `not our bug` can be used for everything that is not our bug (regardless of whether it has been fixed upstream), but sometimes people prefer or request that we keep an issue open here even when all we're doing is waiting for an upstream fix to trickle down to us, which is what the `waiting for upstream` label is for.

> In this case, the problem _has_ been fixed upstream, but dom0 has an old version that still has the bug.

Yeah, so I've applied the `waiting for upstream` label, and I suppose we can just leave this open until we've updated dom0 to a newer Fedora release that contains the upstream fix, which I'm guessing will be in Qubes 4.2.

**Comment by jamke** [comment]
> Reopening, as “not our bug” is for bugs not yet fixed upstream. In this case, the problem _has_ been fixed upstream, but dom0 has an old version that still has the bug.

@DemiMarie @andrewdavidwong 

The issue #7880 is also reproducible in the current updated Qubes OS R4.1.1 but the problem was fixed (I'm not sure it was actually) in the same version of xfce that we already use in Qubes OS. Should it be also somehow changed or reopened?

**Comment by DemiMarie** [comment]
> > Reopening, as “not our bug” is for bugs not yet fixed upstream.
> 
> Technically, `R: not our bug` can be used as a resolution when closing any issue that is not our bug (regardless of whether it has been fixed upstream), but sometimes people prefer or request that we keep an issue open here even when all we're doing is waiting for an upstream fix to trickle down to us, which is what the `waiting for upstream` label is for.

There are also cases where a problem is severe enough to manually backport the fix.  This is not one of them, IMO.

> > In this case, the problem _has_ been fixed upstream, but dom0 has an old version that still has the bug.
> 
> Yeah, so I've applied the `waiting for upstream` label, and I suppose we can just leave this open until we've updated dom0 to a newer Fedora release that contains the upstream fix, which I'm guessing will be in Qubes 4.2.

Yeah

**Comment by andrewdavidwong** [comment]
> The issue #7880 is also reproducible in the current updated Qubes OS R4.1.1 but the problem was fixed (I'm not sure it was actually) in the same version of xfce that we already use in Qubes OS. Should it be also somehow changed or reopened?

If you're asking about #7880, please comment on that issue.
