### ISSUE TITLE
Rick-click on any App shortcut from Qubes Application Menu causes weird output/behavior

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#8400]
### Qubes OS release

4.2

### Steps to reproduce

- Go to Qubes Application Menu
- Rick click on xfce-dom0 (image 1 behavior)
- Rick click on xfce-any other appvm (image 2 behavior)

Note: The Qubes Application Menu will disappear once you right-click with the mouse, and what remains is what you see in images 1 and 2.

### Expected behavior

- Either do something useful
- Or do nothing

### Actual behavior

* Image 1: 

![rightclickdom0](https://github.com/QubesOS/qubes-issues/assets/11895339/3bce5521-4511-445c-87b2-fb09638f3b58)

* Image 2 (dunno what/which favorite talked about here): 

![rightclickothers](https://github.com/QubesOS/qubes-issues/assets/11895339/328186d2-3a89-4cd4-a615-89a0f0f3df86)

**Comment by marmarta** [comment]
I can't reproduce this - which version of the menu do you have? ( `rpm -qa | grep qubes-desktop-linux-menu`) in dom0

**Comment by TNTBOMBOM** [comment]
> I can't reproduce this

Better when you are on new workspace when you open the qubes menu so that you see the effect clearly. 

> which version of the menu do you have?

```
user@dom0 ~]$ rpm -qa | grep qubes-desktop-linux-menu
qubes-desktop-linux-menu-1.1.1-1.fc37.noarch
```

**Comment by marmarta** [comment]
Ok, this should be fixed in the newer versions (1.1.4 in particular); I'm not sure if they are out of current-testing yet, though.

**Comment by TNTBOMBOM** [comment]
> Ok, this should be fixed in the newer versions (1.1.4 in particular)

Sadly at the moment i have 1.1.5 and still happening, what you need to do is simple: 

- Go to Qubes Application Menu
- search for xfce
- Go to dom0
- Right click where the arrow is
 
![rightclickdom01](https://github.com/QubesOS/qubes-issues/assets/11895339/1d0c7e79-6786-4e8a-ae34-9e0de6e9cee5)

You will get image 1 behavior posted at the top.

**Comment by marmarta** [comment]
Thank you, this indeed allowed me to reproduce it.
