### ISSUE TITLE
fido2 implementation breaks on Debian-based sys-usb

### ISSUE THREAD

**Issue by ctr49** [QubesOS/qubes-issues#8529]
It seems [#31](https://github.com/QubesOS/qubes-app-u2f/pull/31) requires python3-fido2 >= 1.0.0 (only then [AttestationResponse was introduced for tap](https://github.com/Yubico/python-fido2/commit/9c0d468419e78c20fe290d49efbd816c92227eaa)).

However, Debian ships with lower versions (Bullseye with 0.8.1, Bookworm with 0.9.1) so this will not work on a Debian-based sys-usb.

_Originally posted by @ctr49 in https://github.com/QubesOS/qubes-app-u2f/issues/31#issuecomment-1704352667_

**Comment by andrewdavidwong** [comment]
Does this affect 4.1 or 4.2 (or both)?

**Comment by marmarek** [comment]
On Debian 12 (stable, bookworm), we've added newer python-fido2 to our repository. On older Debian it isn't that easy, so it's going to stay on older qubes-u2f package.
On R4.1, qubes-ctap never went out of testing repository, so users with Debian 11 and just stable repositories are unaffected.

But those with Debian 11 having either testing repositories enabled, or having R4.2 already (where qubes-ctap landed in stable repo) will need to downgrade qubes-u2f package on debian-11 manually. I haven't tested it, but something like this should work:
```
apt-get update
apt-get remove qubes-ctap
apt-get --allow-downgrades install "qubes-u2f=1.*"
```

**Comment by zpc0** [comment]
Since R4.2 only support Debian 12 and this issue is fixed in Debian 12, I think "affect-4.2" can be removed.

**Comment by arkenoi** [comment]
does not work for me for debian 12 bookworm. still get obsolete python3-fido2 0.9 and qubes-ctap does not get installed because of that.
