### ISSUE TITLE
pulseaudio (17.0-1) breaks dependency 'pulseaudio<=16.1' required by qubes-vm-pulseaudio

### ISSUE THREAD

**Issue by jobforacowboy** [QubesOS/qubes-issues#8875]
### Qubes OS release

4.2

Can we add new  headers for pulseaudio 17.0-1 to qubes-gui-agent-linux?

https://lists.freedesktop.org/archives/pulseaudio-discuss/2024-January/032426.html

```

❯ sudo pacman -Suuy
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing pulseaudio (17.0-1) breaks dependency 'pulseaudio<=16.1' required by qubes-vm-pulseaudio

```

**Comment by james-callahan** [comment]
Can we get a tagged release of qubes-gui-agent-linux?

**Comment by marmarek** [comment]
Yes, but that won't help with Arch updates yet. The builder for our Arch packages is out of order, it should be (hopefully) fixed next week.

**Comment by alimirjamali** [comment]
I believe this issue is already solved and could be closed.

pulseaudio 17.0-3 and qubes-vm-pulseaudio 4.2.10-1 could be installed on archlinux template on Qubes 4.2 without any conflicts.

**Comment by na--** [comment]
I am not sure that is the case:

```
[root@vm ~]# pacman -Syu
:: Synchronizing package databases...
 qubes-r4.2-current is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing pulseaudio (17.0-3) breaks dependency 'pulseaudio<=16.99.1' required by qubes-vm-pulseaudio
[root@vm ~]# cat /etc/pacman.d/90-qubes-4.2-current.conf
[qubes-r4.2-current]
Server = https://archlinux.qubes-os.org/r4.2/current/vm/archlinux/pkgs
```

Also, https://archlinux.qubes-os.org/r4.2/current/vm/archlinux/pkgs/ doesn't really contain any recent qubes-vm-pulseaudio packages, the most recent is:
```
qubes-vm-pulseaudio-4.2.10-1-x86_64.pkg.tar.zst    30-Oct-2023 05:01               15569
qubes-vm-pulseaudio-4.2.10-1-x86_64.pkg.tar.zst..> 30-Oct-2023 05:03                 119
```

**Comment by lubellier** [comment]
@alimirjamali Are you using the current-testing repository ?
@na-- : From my point of view, the issue fixed in current-testing, not in current. I tested by switching to current-testing.

**Comment by alimirjamali** [comment]
@lubellier You are right. I am using the testing repos for my main arch template. I checked again on the current and it is not yet fixed. And the actual working version of qubes-vm-pulseaudio is 4.2.13-1

**Comment by alimirjamali** [comment]
> From my point of view, the issue fixed in current-testing, not in current. I tested by switching to current-testing.

Isn't this merged to current stream already? Couldn't the issue be closed?
