### ISSUE TITLE
Archlinux: thunar extension doesn't work

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9740]
## Observation

openQA test in scenario qubesos-4.3-templates-x86_64-system_tests_gui_interactive@64bit fails in
[gui_filecopy](https://openqa.qubes-os.org/tests/126915/modules/gui_filecopy/steps/16)

![Image](https://github.com/user-attachments/assets/911cdadb-fec0-4553-be4e-68a7d2ff9235)

The "copy to other qube" etc entries are not there.

## Reproducible

Fails since (at least) Build [2025012605-4.3-archlinux](https://openqa.qubes-os.org/tests/126883)

## Expected result

Last good: [2025012522-4.3-archlinux](https://openqa.qubes-os.org/tests/126796) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=templates&machine=64bit&test=system_tests_gui_interactive&version=4.3)

**Comment by ben-grande** [comment]
Fixed on R4.3.

**Comment by Saduff** [comment]
I just installed the latest archlinux template version 4.3.0-202603132335 and still don't see the "copy/move to other qube" menu entries in Thunar. What am I doing wrong?

Update: apparently `qubes-vm-thunar` is not installed by default. However, the menu entries still did not appear after installing that and restarting the template VM.

**Comment by besendorf** [comment]
Did you also restart the AppVMs after restarting the templates? It works fine for me

**Comment by Saduff** [comment]
> Did you also restart the AppVMs after restarting the templates? It works fine for me

I've just been testing in the TemplateVM's Thunar. I tested an AppVM now (created a brand new AppVM) and they don't appear there either.

Anyway, I found out how to make them appear now, but I shouldn't have to do this manually, it should be in the template already.

`qubes-vm-thunar` installs just 2 files:

* `/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/thunar.xml`
* `/usr/lib/qubes/uca_qubes.xml`

"Copy to other qube" and other actions are in `/usr/lib/qubes/uca_qubes.xml`, but Thunar is not going to load them from there. So I manually copied the actions from `/usr/lib/qubes/uca_qubes.xml` and appended them to `/etc/xdg/Thunar/uca.xml`. Then I deleted `~/.config/Thunar/uca.xml` and ran Thunar. Then Thunar will recreate `~/.config/Thunar/uca.xml` based on `/etc/xdg/Thunar/uca.xml` and will include the Qubes actions.

There's a Thunar MR that adds support for several `uca.d` directories for drop-in configuration, but seems like it was never merged: https://gitlab.xfce.org/xfce/thunar/-/merge_requests/111

**Comment by heinrich5991** [comment]
I can confirm that this bug still exists in the current Arch Linux template. Could someone reopen this bug? Or should I open a new bug report?

Following @Saduff's advice worked for me, installing `qubes-vm-thunar`, manually patching `/etc/xdg/Thunar/uca.xml` using stuff from `/usr/lib/qubes/uca_qubes.xml` and deleting `~/.config/Thunar`.

**Comment by ben-grande** [comment]
It seems that Archlinux is missing this post installation hook:

- Debian uses: https://github.com/QubesOS/qubes-core-agent-linux/blob/main/debian/qubes-core-agent-thunar.postinst
- Fedora uses: https://github.com/QubesOS/qubes-core-agent-linux/blob/8a74a7db7b8f83e13b31055cafa8a2f0cc7deba9/rpm_spec/core-agent.spec.in#L713

It seems that a hook could be created similar to: https://github.com/QubesOS/qubes-core-agent-linux/blob/main/archlinux/PKGBUILD.qubes-update-desktop-icons.hook.
